// Dedicated procedure workspaces: 입국재심 · 난민 회부심사 · 출입국사범 조사 · 입국불허 후 송환.
import { $, $$, byId, esc } from './dom.js';
import { state } from '../state.js';
import { current, screeningNo } from '../engines/queue-engine.js';
import { getTraveler } from '../engines/traveler-engine.js';
import { behaviorBand } from '../engines/behavior-engine.js';
import { languageLabel, languageModeLabel } from '../engines/language-engine.js';
import { stageText, procedureMeta, secondaryReasonList, refugeeTimeline, repatriationTimeline, ARREST_REQUIREMENTS } from '../engines/legal-engine.js';
import { clueStats, questionUnlocked } from '../engines/clue-engine.js';
import { travelPartyFor, partyCrossCheck, partyStatusForTraveler } from '../engines/companion-engine.js';
import { lookupName } from '../engines/case-engine.js';
import { notify } from '../services/bus.js';

let focusReturn = null;
export function isProcedureOpen() { return byId('procedureScreen')?.classList.contains('on'); }
export function openProcedureScreen(mode, handlers) {
  state.procedureMode = mode; const e = byId('procedureScreen'); const wasOpen = e.classList.contains('on');
  if (!wasOpen) focusReturn = document.activeElement;
  e.dataset.mode = mode; e.classList.add('on', 'proc-enter'); e.setAttribute('aria-hidden', 'false'); document.body.classList.add('has-procedure');
  notify.sound('procedure', mode); renderProcedureScreen(handlers);
  clearTimeout(openProcedureScreen.t); openProcedureScreen.t = setTimeout(() => e.classList.remove('proc-enter'), 360);
  if (!wasOpen) setTimeout(() => byId('procClose')?.focus(), 0);
}
export function closeProcedureScreen() {
  const e = byId('procedureScreen'); if (!e) return; const wasOpen = e.classList.contains('on');
  e.classList.remove('on'); e.setAttribute('aria-hidden', 'true'); document.body.classList.remove('has-procedure'); state.procedureMode = null;
  if (wasOpen && focusReturn && document.contains(focusReturn)) { const f = focusReturn; focusReturn = null; setTimeout(() => f.focus(), 0); }
}

function languageProcedureBlock() { const l = state.language; if (!l) return ''; const sjpRequired = state.investigation && l.korean < 3 && !l.interpreterActive; return `<div class="proc-language"><div class="proc-language-head"><span>언어·통역 · 판정근거 아님</span><b>${esc(languageModeLabel())}</b></div><div class="proc-language-grid"><div><span>주언어</span><b>${esc(l.primary)}</b></div><div><span>한국어</span><b>${esc(languageLabel(l.korean))}</b></div><div><span>영어</span><b>${esc(languageLabel(l.english))}</b></div></div><div class="proc-language-note ${sjpRequired ? 'warn' : ''}">${sjpRequired ? '출입국사범 신문 단계에서는 한국어가 통하지 않는 용의자의 진술을 통역인에게 통역하게 해야 합니다. 통역을 확보하십시오.' : l.interpreterActive ? `${esc(l.primary)} 통역 지원이 연결되어 있습니다.` : '직접 의사소통이 부족하면 통역을 호출하십시오.'}</div>${!l.interpreterActive ? `<button type="button" class="proc-interpreter-btn" data-proc-act="interpreter">${esc(l.primary)} 통역 호출</button>` : ''}</div>`; }
export function partyProcedureBlock() {
  const party = travelPartyFor(); if (!party) return ''; const x = partyCrossCheck(party);
  const chips = party.members.map((m) => { const t = getTraveler(m.travelerId), st = partyStatusForTraveler(t.id); return `<div class="party-proc-chip"><img src="${t.portrait}" alt=""><span>${esc(t.name.korean)}<br>${esc(m.relation)} · ${st === 'done' ? '처리완료' : st === 'current' ? '현재심사' : '대기'}</span></div>`; }).join('');
  let compare = ''; if (x.archives.length) compare = `<div class="party-compare"><h4>앞서 처리된 동행인 진술</h4>${x.archives.map((a) => `<div class="party-compare-row"><b>${esc(a.name)}</b><span>${esc(a.stay)} · ${esc(a.hotel)}</span><span>${esc(a.summary)}</span></div>`).join('')}${x.status === 'review' ? '<div class="party-conflict">일부 일정 설명 차이가 있습니다. 공동예약과 숙소가 일치하더라도 개별 자유일정 차이는 별도로 소명할 수 있으며, 차이 자체가 입국불허 사유는 아닙니다.</div>' : ''}</div>`;
  return `<div class="party-proc"><div class="party-proc-head"><b>동행여행 교차검증</b><small>${esc(party.label)} · ${esc(party.sharedPNR)}</small></div><div class="party-proc-members">${chips}</div><div class="party-proc-note">같은 PNR·숙소·동행관계는 진술 교차검증 자료입니다. 가족·단체여행이라는 이유 자체로 불리하게 판단하지 않습니다.</div>${compare}</div>`;
}
function procCluePanel(c) { if (!c.clues) return ''; const st = clueStats(c); const cards = st.got.slice().reverse().slice(0, 5).map((x) => `<div class="clue ${esc(x.kind || 'context')}"><strong>${esc(x.title)}${x.key ? '<span class="cluekey">핵심</span>' : ''}</strong><p>${esc(x.text)}</p></div>`).join(''); return `<div class="proc-clues"><div class="proc-section-title"><span>확보 단서</span><small>핵심 ${st.keyGot.length}/${st.keys.length}</small></div><div class="cluecards">${cards || '<div class="clueempty">아직 연결된 단서 없음</div>'}</div></div>`; }
function procPersonCard(c, t, extra = '') { const bb = behaviorBand(), bh = state.behavior || { stress: 0, rapport: 0, profile: { name: '-' } }; return `<div class="proc-card"><div class="proc-card-h"><span>대상자</span><small>${esc(screeningNo())}</small></div><div class="proc-pad"><div class="proc-person"><img src="${t.portrait}" alt="${esc(t.name.korean)} 가상 여행객 초상"><div><div class="proc-name">${esc(t.name.korean)}</div><div class="proc-roman">${esc(t.name.latin)}</div><div class="proc-tags"><span class="proc-tag accent">${esc(stageText(state.stage))}</span><span class="proc-tag">${esc(t.nationality.korean)}</span></div></div></div><div class="proc-behavior"><div class="proc-behavior-head"><span>상호작용 상태 · 판정근거 아님</span><b>${esc(bb.label)} · ${esc(bh.profile.name)}</b></div><div class="proc-behavior-bars"><div class="proc-behavior-item"><span><em>긴장도</em><b>${bh.stress}</b></span><i style="--v:${bh.stress}%" data-tone="stress"></i></div><div class="proc-behavior-item"><span><em>협조도</em><b>${bh.rapport}</b></span><i style="--v:${bh.rapport}%" data-tone="rapport"></i></div></div></div>${languageProcedureBlock()}${partyProcedureBlock()}<div class="proc-facts"><div class="proc-fact"><span>여권번호</span><b>${esc(c.passport)}</b></div><div class="proc-fact"><span>입국기반</span><b>${esc(c.basis)}</b></div><div class="proc-fact"><span>방문목적</span><b>${esc(c.purpose)}</b></div><div class="proc-fact"><span>체류예정</span><b>${esc(c.stay)}</b></div><div class="proc-fact"><span>입국편</span><b>${esc(c.arrival.split(' · ')[0])}</b></div></div>${extra}${procCluePanel(c)}</div></div>`; }
const qRow = (q, verb = '질문') => `<div class="proc-row"><span class="dot">?</span><span>${esc(q.q)}</span><button type="button" data-proc-q="${esc(q.id)}">${verb}</button></div>`;

function renderSecondaryProcedure(c, t) {
  const reasons = secondaryReasonList(c); const first = c.initial || '최초 진술 기록 없음'; const latest = state.logs.filter((x) => x.type === 'alien').slice(-1)[0]?.text || first;
  const qs = (c.questions || []).filter((q) => !state.asked.has(q.id) && questionUnlocked(q)).slice(0, 7); const lookups = ['history', 'visa', 'pnr', 'contact', ...(travelPartyFor(c) ? ['party'] : []), 'public'];
  return `<div class="proc-grid">${procPersonCard(c, t, `<div class="proc-law"><b>재심의 성격</b><br>재심은 별도의 제재처분이 아니라 출입국관리법 제12조에 따른 입국심사의 계속입니다.</div>`)}<div class="proc-card"><div class="proc-card-h"><span>진술·소명 검토</span><small>PRIMARY ↔ SECONDARY</small></div><div class="proc-pad"><div class="proc-alert"><strong>재심 인계 사유</strong>${reasons.map((x) => '• ' + esc(x)).join('<br>')}</div><div class="proc-section"><div class="proc-section-title"><span>진술 비교</span><small>자동 모순 검토 보조</small></div><div class="statement-pair"><div class="statement"><h4>최초 진술</h4><p>${esc(first)}</p></div><div class="statement-arrow" aria-hidden="true">→</div><div class="statement"><h4>현재까지 확인된 진술</h4><p>${esc(latest)}</p></div></div>${first !== latest ? '<div class="conflict">진술 내용이 변경되었습니다. 변경 자체가 위반사실을 의미하지 않으며 추가 소명이 필요합니다.</div>' : ''}</div><div class="proc-section"><div class="proc-section-title"><span>추가 질문</span><small>${state.asked.size}개 완료</small></div><div class="proc-list">${qs.length ? qs.map((q) => qRow(q)).join('') : '<div class="proc-row done"><span class="dot">✓</span><span>추가 질문 완료</span><span></span></div>'}</div></div></div></div><div class="proc-card"><div class="proc-card-h"><span>재심 작업목록</span><small>증거·전산조회</small></div><div class="proc-pad"><div class="proc-list">${lookups.map((k) => `<div class="proc-row ${state.looked.has(k) ? 'done' : ''}"><span class="dot">${state.looked.has(k) ? '✓' : '·'}</span><span>${esc(lookupName(k))}</span><button type="button" data-proc-lu="${k}">${state.looked.has(k) ? '재조회' : '조회'}</button></div>`).join('')}</div><div class="proc-actions"><button type="button" class="proc-action good" data-proc-act="clear"><b>입국 허가</b><small>소명이 완료된 경우</small></button><button type="button" class="proc-action danger" data-proc-act="refuse"><b>입국불허 검토</b><small>법정 사유 선택</small></button>${c.special === 'refugee' ? '<button type="button" class="proc-action primary wide" data-proc-act="refugee"><b>난민신청·회부심사</b><small>난민법 제6조 전용 절차로 이동</small></button>' : ''}${c.special === 'forgery' ? '<button type="button" class="proc-action primary wide" data-proc-act="sjp"><b>문서감식·사범조사</b><small>구체적 범죄혐의 확인 절차</small></button>' : ''}<button type="button" class="proc-action wide" data-proc-act="back"><b>일반 심사대 보기</b><small>재심 상태를 유지한 채 원 화면 확인</small></button></div></div></div></div>`;
}
function renderRefugeeProcedure(c, t) {
  const step = state.refugeeStep; const timeline = refugeeTimeline(step); const facts = ['정치적 박해 주장: 확인되지 않음', '종교적 박해 주장: 확인되지 않음', '특정 사회집단·정치적 견해 관련 박해 진술: 확인되지 않음', '취업·소득 목적 진술: 반복 확인'];
  const rq = (c.questions || []).filter((q) => !state.asked.has(q.id) && questionUnlocked(q) && (q.cat === '난민' || q.cat === '직업' || q.cat === '추가소명')).slice(0, 5);
  return `<div class="proc-grid">${procPersonCard(c, t, `<div class="proc-law"><b>절차상 주의</b><br>불회부 결정은 입국불허와 동일한 처분이 아닙니다. 불회부 후 출입국관리법에 따른 입국심사로 돌아갑니다.</div>`)}<div class="proc-card"><div class="proc-card-h"><span>회부심사 기록</span><small>최대 7일 · 게임상 시간 압축</small></div><div class="proc-pad"><div class="proc-section"><div class="proc-section-title"><span>절차 타임라인</span><small>난민법 제6조</small></div><div class="proc-timeline">${timeline.map(([x, d], i) => `<div class="proc-step ${d ? 'done' : i === step ? 'active' : ''}"><b>${x}</b><p>${d ? '완료' : '대기'}</p></div>`).join('')}</div></div><div class="proc-section"><div class="proc-section-title"><span>인터뷰상 확인사항</span><small>사건 데이터</small></div><div class="proc-list">${facts.map((x, i) => `<div class="proc-row ${i === 3 ? 'warn' : 'done'}"><span class="dot">${i === 3 ? '!' : '✓'}</span><span>${x}</span><span></span></div>`).join('')}</div>${rq.length ? `<div class="proc-section"><div class="proc-section-title"><span>회부심사 인터뷰</span><small>진술 구체화</small></div><div class="proc-list">${rq.map((q) => qRow(q)).join('')}</div></div>` : ''}</div></div></div><div class="proc-card"><div class="proc-card-h"><span>회부심사 결정</span><small>난민법 시행령 제5조</small></div><div class="proc-pad"><div class="proc-alert"><strong>현재 단계</strong>${step === 1 ? '난민인정 신청이 접수되었습니다. 회부 여부 심사를 개시하십시오.' : step === 2 ? '회부 여부를 판단할 수 있습니다. 이 케이스의 인터뷰·자료를 검토하십시오.' : step >= 4 ? '불회부 결정 후 입국심사로 복귀했습니다.' : '난민신청 절차를 진행하십시오.'}</div><div class="proc-actions">${step === 1 ? '<button type="button" class="proc-action primary wide" data-proc-act="start-referral"><b>회부심사 개시</b><small>REFERRAL SCREENING</small></button>' : ''}${step === 2 ? '<button type="button" class="proc-action danger wide" data-proc-act="non-referral"><b>난민인정심사 불회부</b><small>시행령 제5조제1항제7호 · 게임상 사실관계</small></button><button type="button" class="proc-action wide" data-proc-act="refer"><b>난민인정심사 회부</b><small>이 사건에서는 근거가 부족한 선택</small></button>' : ''}${step >= 4 ? '<button type="button" class="proc-action primary wide" data-proc-act="secondary"><b>입국심사로 복귀</b><small>제12조상 입국 여부를 별도로 판단</small></button>' : ''}<button type="button" class="proc-action wide" data-proc-act="back"><b>일반 심사대 보기</b><small>현재 절차 상태 유지</small></button></div><div class="proc-law"><b>공개 법령 근거</b><br>난민법 제6조: 출입국항에서 난민인정신청서를 제출한 사람에 대해 7일 이내 회부 여부 결정. 시행령 제5조제1항제7호: 오로지 경제적 이유 등 신청이 명백히 이유 없는 경우 불회부 가능.</div></div></div></div>`;
}
function renderSjpProcedure(c, t) {
  const pt = getTraveler(c.passportPortraitId || c.travelerId) || t;
  const evidence = [['문서 감식', state.forensic, state.forensic ? '위·변조 판정 확보' : '전자칩/MRZ 이상 정밀확인 필요'], ['출입국사범 조사', state.investigation, state.investigation ? '조사 착수·분리 기록' : '감식 후 구체적 혐의 확립 필요'], ['긴급체포 요건', state.arrestReview, state.arrestReview ? '요건별 검토 단계' : '자동 체포 금지']];
  const fq = (c.questions || []).filter((q) => !state.asked.has(q.id) && questionUnlocked(q) && (q.cat === '기본사항' || q.cat === '추가소명' || q.cat === '국내관계')).slice(0, 4);
  return `<div class="proc-grid">${procPersonCard(c, t, `<div class="proc-law"><b>특별사법경찰 범위</b><br>출입국관리 업무 종사 4~7급 공무원은 법정 범위의 출입국관리에 관한 범죄 등에 대해 사법경찰관 직무를 수행합니다.</div>`)}<div class="proc-card"><div class="proc-card-h"><span>신원·문서 감식</span><small>실제 얼굴 ↔ 여권상 명의</small></div><div class="proc-pad"><div class="proc-compare"><div class="photo"><img src="${pt.portrait}" alt="여권상 명의 사진"><label>여권/칩 사진</label></div><div class="proc-vs" aria-hidden="true">≠</div><div class="photo"><img src="${t.portrait}" alt="피심사인 현재 얼굴"><label>피심사인</label></div></div><div class="proc-alert"><strong>전자문서 이상</strong>CHIP SIGNATURE ERROR · MRZ CHECKSUM FAIL · 생체정보 중대한 불일치</div><div class="proc-list">${evidence.map(([a, d, b]) => `<div class="proc-row ${d ? 'done' : 'warn'}"><span class="dot">${d ? '✓' : '!'}</span><span><b>${a}</b><br>${b}</span><span></span></div>`).join('')}</div>${fq.length ? `<div class="proc-section"><div class="proc-section-title"><span>조사 후속 질문</span><small>감식·조사 결과에 따라 해금</small></div><div class="proc-list">${fq.map((q) => qRow(q, '신문')).join('')}</div></div>` : ''}</div></div><div class="proc-card"><div class="proc-card-h"><span>${state.stage === 'ARREST_REVIEW' ? '긴급체포 요건' : '조사 조치'}</span><small>${state.stage === 'ARREST_REVIEW' ? '형사소송법 제200조의3' : '출입국관리법 제47·48조'}</small></div><div class="proc-pad">${state.stage === 'ARREST_REVIEW' ? `<div class="arrest-check">${ARREST_REQUIREMENTS.map((r) => `<label><input type="checkbox" class="proc-ar"> ${esc(r)}</label>`).join('')}</div><button type="button" class="proc-action danger wide" data-proc-act="execute-arrest"><b>긴급체포 집행</b><small>모든 법정요건 확인 후</small></button>` : `<div class="proc-actions">${!state.forensic ? '<button type="button" class="proc-action primary wide" data-proc-act="forensic"><b>여권·문서 감식 의뢰</b><small>위변조 의심 문서 진위 확인</small></button>' : ''}${state.forensic && !state.investigation ? '<button type="button" class="proc-action primary wide" data-proc-act="investigate"><b>출입국사범 조사 전환</b><small>입국심사와 형사·행정 조사를 분리 기록</small></button>' : ''}${state.investigation ? '<button type="button" class="proc-action danger wide" data-proc-act="arrest-review"><b>긴급체포 요건 검토</b><small>위조여권 발견만으로 자동 체포하지 않음</small></button>' : ''}<button type="button" class="proc-action wide" data-proc-act="back"><b>일반 심사대 보기</b><small>현재 조사 상태 유지</small></button></div>`}<div class="proc-law"><b>조사 기록 원칙</b><br>출입국관리법 제48조상 용의자 신문은 다른 출입국관리공무원이 참여하고, 진술은 조서에 기록하는 구조입니다. 일반 입국재심 인터뷰와 구분합니다.</div></div></div></div>`;
}
function renderRepatriationProcedure(c, t) {
  const step = state.repatriationStep || 0; const tl = repatriationTimeline(step);
  return `<div class="proc-grid">${procPersonCard(c, t, `<div class="proc-law"><b>INAD 표시</b><br>INAD는 게임상·항공운송상 상태표시이며 대한민국 법률상 처분명은 ‘입국 불허가’입니다.</div>`)}<div class="proc-card"><div class="proc-card-h"><span>송환 절차 타임라인</span><small>ENTRY REFUSED → REPATRIATION</small></div><div class="proc-pad"><div class="proc-timeline">${tl.map(([a, d, b], i) => `<div class="proc-step ${d ? 'done' : i === step + 1 ? 'active' : ''}"><b>${a}</b><p>${b} · ${d ? '완료' : '대기'}</p></div>`).join('')}</div><div class="proc-alert"><strong>운수업자</strong>${esc(c.carrier)} · 입국편 ${esc(c.arrival)}<br>송환대상 외국인을 비용과 책임으로 대한민국 밖으로 송환하는 절차를 진행합니다.</div></div></div><div class="proc-card"><div class="proc-card-h"><span>후속 집행</span><small>법정서식·대기장소</small></div><div class="proc-pad"><div class="proc-actions">${step === 0 ? '<button type="button" class="proc-action primary wide" data-proc-act="repat-order"><b>송환지시서 발급</b><small>운수업자에게 제76조에 따른 송환지시</small></button>' : ''}${step === 1 ? '<button type="button" class="proc-action primary wide" data-proc-act="waiting-room"><b>출국대기실 인계</b><small>제76조의2 · 국가 관리 출국대기실</small></button>' : ''}${step >= 2 ? '<button type="button" class="proc-action good wide" data-proc-act="finish-refusal"><b>송환대기 처리 완료</b><small>사건을 종결하고 다음 승객 호출</small></button>' : ''}</div><div class="proc-law"><b>송환대기장소</b><br>송환대상외국인은 출국 전까지 출국대기실에서 대기하는 것이 원칙이며, 법정 예외에 따라 출입국항 내 지정장소에서 조건부 대기가 가능합니다.</div></div></div></div>`;
}
export function renderProcedureScreen(handlers) {
  if (!state.procedureMode) return; const c = current(), t = getTraveler(c.travelerId), meta = procedureMeta(state.procedureMode);
  byId('procTitle').textContent = meta[0]; byId('procKicker').textContent = meta[1]; byId('procSubtitle').textContent = meta[2];
  const body = state.procedureMode === 'secondary' ? renderSecondaryProcedure(c, t) : state.procedureMode === 'refugee' ? renderRefugeeProcedure(c, t) : state.procedureMode === 'sjp' ? renderSjpProcedure(c, t) : renderRepatriationProcedure(c, t);
  byId('procBody').innerHTML = body;
  if (!handlers) return;
  $$('#procBody [data-proc-q]').forEach((b) => { b.onclick = () => handlers.ask(b.dataset.procQ); });
  $$('#procBody [data-proc-lu]').forEach((b) => { b.onclick = () => handlers.lookup(b.dataset.procLu); });
  $$('#procBody [data-proc-act]').forEach((b) => { b.onclick = () => handlers.act(b.dataset.procAct, { checked: $$('#procBody .proc-ar:checked').length }); });
}
