// Records centre, replays, player profile, achievements, missions, challenge boards, operations log.
import { $$, byId, esc, fmtDate, fmtClock } from '../dom.js';
import { showModal, closeModal } from '../modals.js';
import { state, session } from '../../state.js';
import { getTraveler } from '../../engines/traveler-engine.js';
import { loadMeta, saveMeta, emptyMeta, loadProgressSave, clearProgressSave } from '../../engines/save-engine.js';
import { ACHIEVEMENTS, CHALLENGES, DAILY_MISSION_DEFS, careerTemplate, levelInfo, careerTitle, dailySnapshot, challengeCfg, challengeEvaluation } from '../../engines/achievement-engine.js';
import { SCENARIOS } from '../../../data/operations.js';
import { difficultyName, difficultyCfg, scenarioCfg, eventEffectText } from '../../engines/operation-engine.js';
import { operationalScore } from '../../engines/score-engine.js';
import { displayDateKo } from '../../engines/rng.js';
import { toast } from '../toast.js';

export function sessionLawCounts(sessions) { const map = new Map(); for (const s of sessions) for (const m of (s.mistakes || [])) { const k = m.lawRef || '기타 절차'; map.set(k, (map.get(k) || 0) + 1); } return [...map.entries()].sort((a, b) => b[1] - a[1]); }

export function showCaseReplay(sessionId, idx) {
  const meta = loadMeta(), sess = meta.sessions.find((x) => x.id === sessionId), r = sess?.reports?.[idx]; if (!sess || !r) return; const t = getTraveler(r.travelerId);
  showModal(`사건 리플레이 · ${r.screening || String(idx + 1)}`, `<div class="report-person">${t ? `<img src="${t.portrait}" alt="">` : ''}<div><div class="report-name">${esc(r.name || t?.name?.korean || '가상 여행객')}</div><div class="report-sub">${esc(r.nat || t?.nationality?.korean || '')} · ${esc(r.label || '')}</div></div></div><div class="report"><div class="r"><span>입국기반</span><b>${esc(r.basis || '-')}</b></div><div class="r"><span>방문목적</span><b>${esc(r.purpose || '-')}</b></div><div class="r"><span>법적 기준</span><b>${esc(r.lawRef || '출입국관리법 제12조')}</b></div><div class="r"><span>절차 준수</span><b>${r.procedure ?? '-'}%</b></div><div class="r"><span>처리효율</span><b>${r.caseEff ?? '-'}%</b></div><div class="r"><span>처리시간</span><b>${fmtClock(r.seconds || 0)}</b></div></div><div class="record-section"><h3>수행 절차</h3><div class="replay-timeline">${(r.actions || []).length ? (r.actions || []).map((a) => `<span class="replay-step">${esc(a)}</span>`).join('') : '<span class="record-warning">이전 버전에서 저장된 기록이라 상세 행동 타임라인이 없습니다.</span>'}</div></div>${(r.mistakes || []).length ? `<div class="record-section"><h3>이 사건의 오류 기록</h3>${r.mistakes.map((m) => `<div class="law-mistake-row"><b>${esc(m.lawRef || '절차 오류')}<br><span class="law-mistake-msg">${esc(m.msg || '')}</span></b><span>-${m.pts || 0}</span></div>`).join('')}</div>` : ''}<p class="record-warning">리플레이는 당시 판단과 절차를 복기하는 기록 뷰어입니다. 과거 사건을 다시 채점하거나 현재 세션에 영향을 주지 않습니다.</p>`);
}
export function showSessionReplay(sessionId) {
  const meta = loadMeta(), sess = meta.sessions.find((x) => x.id === sessionId); if (!sess) return;
  showModal(`근무 리플레이 · SESSION ${sess.seed}`, `<div class="records-summary"><div class="record-kpi"><span>등급</span><b>${esc(sess.grade)}</b></div><div class="record-kpi"><span>종합평가</span><b>${sess.overall}</b></div><div class="record-kpi"><span>난이도</span><b class="small">${esc(difficultyName(sess.difficulty))}</b></div><div class="record-kpi"><span>처리 인원</span><b>${sess.stats?.processed || 0}</b></div><div class="record-kpi"><span>특별근무</span><b class="small">${esc(sess.challengeName || '일반 근무')}</b></div><div class="record-kpi"><span>시나리오</span><b class="small">${esc(sess.scenarioName || SCENARIOS[sess.scenarioId || 'normal']?.name || '기본 근무')}</b></div></div><div class="replay-cases">${(sess.reports || []).map((r, i) => { const t = getTraveler(r.travelerId); return `<div class="replay-row">${t ? `<img src="${t.portrait}" alt="">` : '<div></div>'}<div><b>${esc(r.screening || '')} · ${esc(r.name || t?.name?.korean || '가상 여행객')}</b><span>${esc(r.label || '')} · 절차 ${r.procedure ?? '-'}% · ${fmtClock(r.seconds || 0)}</span></div><button type="button" class="record-mini-btn" data-replay-case="${i}">복기</button></div>`; }).join('')}</div><p class="record-warning">저장된 사건기록은 최근 12개 근무까지만 유지합니다.</p>`, { size: 'wide' });
  $$('[data-replay-case]').forEach((b) => { b.onclick = () => showCaseReplay(sessionId, Number(b.dataset.replayCase)); });
}
export function showRecordsCenter({ onResume, onProfile, onBoard, onDaily }) {
  const meta = loadMeta(), sessions = meta.sessions || [], progress = loadProgressSave(); const total = sessions.reduce((a, s) => a + (s.stats?.processed || 0), 0), sCount = sessions.filter((s) => s.grade === 'S').length, avg = sessions.length ? Math.round(sessions.reduce((a, s) => a + (s.overall || 0), 0) / sessions.length) : 0, law = sessionLawCounts(sessions);
  const best = ['training', 'standard', 'realistic'].map((k) => { const b = meta.best?.[k]; return `<div class="difficulty-record"><span>${difficultyName(k)} 최고</span><b>${b?.grade || '-'}</b><span>${b ? `종합 ${b.overall} · ${fmtDate(b.endedAt)}` : '기록 없음'}</span></div>`; }).join('');
  showModal('근무기록 · 진행도 센터', `<div class="records-shell"><div class="progress-card"><b>심사관 게임 경력</b><span>누적 프로필과 업적은 별도로 계속 보존됩니다.</span><div class="record-board-actions"><button type="button" class="record-mini-btn" id="recordsProfile">프로필 보기</button><button type="button" class="record-mini-btn" id="recordsBoard">도전 기록 보드</button><button type="button" class="record-mini-btn" id="recordsDaily">오늘의 미션</button></div></div>${progress ? `<div class="progress-card"><b>저장된 진행 · SESSION ${progress.seed}</b><span>${Math.min(progress.nextIndex, 36)}/36명 처리 · ${difficultyName(progress.difficulty)} · ${fmtDate(progress.savedAt)}</span><button type="button" class="record-mini-btn" id="recordResume">이어하기</button></div>` : ''}<div class="records-summary"><div class="record-kpi"><span>완료 근무</span><b>${sessions.length}</b></div><div class="record-kpi"><span>누적 심사</span><b>${total}</b></div><div class="record-kpi"><span>S 등급</span><b>${sCount}</b></div><div class="record-kpi"><span>평균 종합</span><b>${avg || '-'}</b></div></div><div class="record-section"><h3>난이도별 최고 기록</h3><div class="difficulty-records">${best}</div></div><div class="record-section"><h3>자주 틀린 법조문·절차</h3><div class="law-mistakes">${law.length ? law.slice(0, 6).map(([k, n]) => `<div class="law-mistake-row"><b>${esc(k)}</b><span>${n}회</span></div>`).join('') : '<div class="record-empty">완료된 근무의 법률 오류 기록이 없습니다.</div>'}</div></div><div class="record-section"><h3>최근 근무</h3><div class="session-list">${sessions.length ? sessions.map((sess) => `<div class="session-row-record"><div class="session-grade">${esc(sess.grade)}</div><div class="session-meta"><b>SESSION ${sess.seed} · ${difficultyName(sess.difficulty)} · ${esc(sess.scenarioName || SCENARIOS[sess.scenarioId || 'normal']?.name || '기본 근무')}</b><span>${fmtDate(sess.endedAt)} · 종합 ${sess.overall} · 처리 ${sess.stats?.processed || 0}명 · 오류 ${(sess.mistakes || []).length}건${sess.challengeId && sess.challengeId !== 'none' ? ` · 도전 ${sess.challengeSuccess ? '성공' : '미달'}` : ''}</span></div><div class="session-actions"><button type="button" data-session-replay="${sess.id}">사건 리플레이</button></div></div>`).join('') : '<div class="record-empty">아직 완료한 근무가 없습니다.</div>'}</div></div><div class="records-footer"><span class="record-warning">기록은 이 브라우저에 저장되며 최근 12개 근무를 유지합니다.</span><button type="button" id="resetRecords">기록 초기화</button></div></div>`, { size: 'wide' });
  $$('[data-session-replay]').forEach((b) => { b.onclick = () => showSessionReplay(b.dataset.sessionReplay); });
  byId('recordsProfile').onclick = onProfile; byId('recordsBoard').onclick = onBoard; byId('recordsDaily').onclick = onDaily;
  const rb = byId('recordResume'); if (rb) rb.onclick = () => { closeModal(); onResume(); };
  byId('resetRecords').onclick = () => { showModal('근무기록 초기화', `<p class="modal-note">완료된 근무기록과 자동저장 체크포인트를 모두 삭제합니다. 이 작업은 되돌릴 수 없습니다.</p><button type="button" class="act refuse block" id="confirmResetRecords"><strong>기록 초기화</strong></button>`); byId('confirmResetRecords').onclick = () => { saveMeta(emptyMeta()); clearProgressSave(); closeModal(); toast('근무기록을 초기화했습니다.'); }; };
}
export function showPlayerProfile() {
  const meta = loadMeta(), c = meta.career || careerTemplate(), lv = levelInfo(c.xp), unlocked = ACHIEVEMENTS.filter((a) => c.achievements?.[a.id]).length;
  const stats = [['완료 근무', c.completedShifts], ['누적 심사', c.totalPassengers], ['무오류 승객', c.cleanPassengers], ['업적', `${unlocked}/${ACHIEVEMENTS.length}`], ['S 등급', c.sGrades], ['재심 후 허가', c.secondaryClears], ['난민 완전처리', c.refugeePerfect], ['특사경 완전처리', c.sjpPerfect], ['특별근무 성공', c.challengeWins || 0], ['일일미션 연속', `${c.dailyStreak || 0}일`], ['시나리오 근무', Object.values(c.scenarioCompleted || {}).reduce((a, n) => a + n, 0)], ['3일 캠페인 완주', c.campaignsCompleted || 0], ['완벽 캠페인', c.campaignPerfect || 0]];
  showModal('심사관 프로필 · 게임 경력', `<div class="profile-shell"><div class="profile-hero"><div class="level-orb"><div><span>LEVEL</span><b>${lv.level}</b></div></div><div class="profile-title"><h3>${careerTitle(lv.level)}</h3><p>게임상 경력 레벨 · 실제 법무부 직급·승진체계와 무관합니다.</p><div class="xp-track" style="--xp:${lv.pct}%"><i></i></div><div class="xp-copy"><span>XP ${c.xp}</span><span>다음 레벨까지 ${Math.max(0, lv.next - c.xp)} XP</span></div></div></div><div class="career-stats">${stats.map(([k, v]) => `<div class="career-stat"><span>${k}</span><b>${v}</b></div>`).join('')}</div><div class="record-section"><h3>업적</h3><div class="achievement-grid">${ACHIEVEMENTS.map((a) => { const on = !!c.achievements?.[a.id]; return `<div class="achievement ${on ? 'unlocked' : 'locked'}"><div class="ach-icon">${esc(a.icon)}</div><b>${esc(a.name)}</b><span>${esc(a.desc)}</span><em>${on ? '해금' : '잠김'}</em></div>`; }).join('')}</div></div><div class="career-note">프로필 수치는 완료된 근무를 기준으로 누적됩니다. 선택형 특별근무·일일 미션 성공 시 XP와 기록이 누적됩니다. 시나리오 프리셋은 운영환경만 조정합니다. 국적·외모·승객 태도는 XP나 업적 계산에 사용되지 않습니다.</div></div>`, { size: 'wide' });
}
export function renderDailyStart(onOpen) { const box = byId('dailyStart'); if (!box) return; const { d, progress } = dailySnapshot(loadMeta(), false), done = d.ids.filter((id) => (progress[id] || 0) >= DAILY_MISSION_DEFS[id].target).length; box.innerHTML = `<div class="daily-start-head"><div><b>오늘의 미션 · ${displayDateKo(d.date)}</b><span>${done}/3 완료 · 전부 완료 보너스 +40 XP</span></div><button type="button" class="daily-open" id="dailyStartOpen">자세히</button></div><div class="daily-mini-list">${d.ids.map((id) => { const x = DAILY_MISSION_DEFS[id], v = progress[id] || 0; return `<div class="daily-mini ${v >= x.target ? 'done' : ''}"><b>${esc(x.name)}</b><span>${Math.min(v, x.target)}/${x.target} · +${x.reward} XP</span></div>`; }).join('')}</div>`; byId('dailyStartOpen').onclick = onOpen; }
export function showDailyMissions() { const meta = loadMeta(), { d, progress } = dailySnapshot(meta, true), c = meta.career || careerTemplate(); showModal('오늘의 미션', `<div class="mission-board"><div class="mission-date"><div><b>${displayDateKo(d.date)} · 오늘의 3개 미션</b><span>진행도는 완료된 근무 기준으로 저장됩니다. 근무 중 수치는 예상치입니다.</span></div><span>연속 ${c.dailyStreak || 0}일 · 최고 ${c.bestDailyStreak || 0}일</span></div><div class="mission-list">${d.ids.map((id) => { const x = DAILY_MISSION_DEFS[id], v = progress[id] || 0, p = Math.min(100, Math.round(v / x.target * 100)); return `<div class="mission-card ${v >= x.target ? 'done' : ''}"><div class="mission-card-head"><b>${esc(x.name)}</b><em>+${x.reward} XP</em></div><p>${esc(x.desc)}</p><div class="mission-track"><i style="width:${p}%"></i></div><div class="mission-progress"><span>${Math.min(v, x.target)}/${x.target}</span><span>${v >= x.target ? '완료' : '진행 중'}</span></div></div>`; }).join('')}</div><div class="daily-reward-strip"><b>오늘의 미션 3종 완료 보너스 · +40 XP</b><span>하루에 한 번만 지급됩니다. 날짜가 바뀌면 새로운 3개 미션이 생성됩니다.</span></div><div class="record-board-actions"><button type="button" class="record-mini-btn" id="dailyBoardBtn">도전 기록 보드</button></div></div>`); byId('dailyBoardBtn').onclick = showChallengeBoard; }
export function showChallengeBoard() { const meta = loadMeta(), c = meta.career || careerTemplate(), ch = Object.values(CHALLENGES).filter((x) => x.id !== 'none'), sc = Object.values(SCENARIOS); showModal('도전 기록 보드', `<div class="mission-board"><div class="streak-hero"><div class="streak-kpi"><span>일일미션 연속</span><b>${c.dailyStreak || 0}</b></div><div class="streak-kpi"><span>최고 연속</span><b>${c.bestDailyStreak || 0}</b></div><div class="streak-kpi"><span>특별근무 연속성공</span><b>${c.challengeStreak || 0}</b></div></div><div class="record-board-grid"><div class="record-board-card"><h4>특별 근무 도전</h4>${ch.map((x) => `<div class="board-row"><span>${esc(x.name)}</span><b>${c.challengeCompleted?.[x.id] || 0}회</b></div>`).join('')}<div class="board-row"><span>최고 연속 성공</span><b>${c.bestChallengeStreak || 0}회</b></div></div><div class="record-board-card"><h4>시나리오 프리셋</h4>${sc.map((x) => `<div class="board-row"><span>${esc(x.name)}</span><b>${c.scenarioCompleted?.[x.id] || 0}회 · 최고 ${c.scenarioBest?.[x.id] || 0}</b></div>`).join('')}</div></div><div class="record-board-card"><h4>일일 미션</h4><div class="board-row"><span>완료한 개별 미션</span><b>${c.dailyMissionCompletions || 0}개</b></div><div class="board-row"><span>3종 전부 완료한 날</span><b>${c.dailyFullDays || 0}일</b></div><div class="board-row"><span>현재 연속 완료</span><b>${c.dailyStreak || 0}일</b></div><div class="board-row"><span>최고 연속 완료</span><b>${c.bestDailyStreak || 0}일</b></div></div></div>`); }
export function showChallengeDetail() { const c = challengeCfg(), e = challengeEvaluation(false); showModal(`특별 근무 도전 · ${c.name}`, `<div class="challenge-panel"><div class="challenge-hero ${['congestion', 'specialist'].includes(c.id) ? 'special' : ''}"><div class="challenge-symbol">${esc(c.symbol)}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.desc)}</p></div><div class="challenge-bonus">${c.bonus ? `성공 +${c.bonus} XP` : '보너스 없음'}</div></div><div class="challenge-rules">${c.rules.map((r, i) => `<div class="challenge-rule"><i>${i + 1}</i><div><b>${esc(r)}</b><span>${c.id === 'none' ? '기본 게임 규칙을 그대로 적용합니다.' : '이 조건은 법률상 정답을 변경하지 않는 게임 목표입니다.'}</span></div></div>`).join('')}</div>${c.id !== 'none' ? `<div class="challenge-progress-card"><h4>현재 진행도 · ${e.pct}%</h4><div class="challenge-progress-track"><i style="width:${e.pct}%"></i></div><p>${esc(e.detail)}</p></div>` : ''}<p class="record-warning">도전과제는 게임 운영 목표와 XP 보너스에만 영향을 줍니다. 승객의 국적·외모·태도 또는 법률상 입국요건을 변경하지 않습니다.</p></div>`); }
export function showOperationsLog() { const e = state.activeEvent; const hist = (state.eventHistory || []).slice().reverse(); showModal('현장 운영기록', `${e ? `<div class="event-detail-card active"><h3>${esc(e.title)}</h3><p>${esc(e.desc)}<br><b>${esc(eventEffectText(e))}</b> · 남은 ${e.remaining}건</p></div>` : '<div class="event-detail-card"><h3>현재 운영상황 정상</h3><p>활성 현장 이벤트가 없습니다.</p></div>'}<div class="duty-grid"><div class="duty-cell"><span>난이도</span><b>${difficultyCfg().label}</b></div><div class="duty-cell"><span>시나리오</span><b>${esc(scenarioCfg().name)}</b></div><div class="duty-cell"><span>현장 이벤트</span><b>${state.eventsSeen}</b></div><div class="duty-cell"><span>휴식</span><b>${state.breaksTaken}</b></div><div class="duty-cell"><span>피로도</span><b>${Math.round(state.fatigue)}</b></div></div><div class="event-detail-card"><h3>특별 근무 도전 · ${esc(challengeCfg().name)}</h3><p>${esc(challengeEvaluation(false).detail)}${challengeCfg().id !== 'none' ? ` · 성공 보너스 +${challengeCfg().bonus} XP` : ''}</p></div><div class="event-history">${hist.length ? hist.map((h) => `<div class="event-history-row"><b>${h.status}</b><span>${esc(h.title)}</span><span>${esc(h.effect)}</span></div>`).join('') : '<div class="event-detail-card"><p>아직 기록된 현장 이벤트가 없습니다.</p></div>'}</div><p class="modal-note">현장 이벤트·피로도·난이도는 게임상 운영 변수입니다. 입국요건·법률상 정답·국적별 판정을 변경하지 않습니다. 음향·안내방송은 접근성 보조와 현장 연출용이며 점수에 영향을 주지 않습니다.</p>`); }
