// Help, quick principles, rules reference (업무참고), tutorial and settings dialogs.
import { $, $$, byId, esc } from '../dom.js';
import { showModal, closeModal } from '../modals.js';
import { state, preferences } from '../../state.js';
import { TUTORIAL_STEPS } from '../../../data/tutorial.js';
import { savePreferences, markTutorialSeen } from '../../engines/save-engine.js';
import { toast } from '../toast.js';

export const SHORTCUT_ROWS = [['1–6', '질문 카테고리 선택'], ['K / E / I', '한국어 / 영어 / 통역'], ['[ / ]', '이전 / 다음 제출서류'], ['H / V / P', '출입국기록 / 사증 / PNR'], ['C / G / O', '국내관계 / 동행인 / 공개정보'], ['Alt+R', '입국재심 인계'], ['Alt+A', '입국 허가'], ['Alt+X', '입국불허 사유 열기'], ['Alt+J', '출입국사범 절차'], ['M', '음향 켜기/끄기'], ['? 또는 F1', '도움말'], ['L', '근무기록'], ['B', '오늘의 미션'], ['U', '심사관 프로필'], ['S', '설정'], ['Esc', '현재 대화상자/절차 닫기']];

export function applyPreferences() {
  document.body.classList.toggle('pref-font-large', preferences.font === 'large'); document.body.classList.toggle('pref-contrast', preferences.contrast); document.body.classList.toggle('pref-reduce-motion', preferences.reduceMotion); document.body.classList.toggle('show-hotkeys', preferences.shortcutHints);
  const live = byId('a11yLive'); if (live) live.textContent = `화면 설정 적용: 글자 ${preferences.font === 'large' ? '크게' : '기본'}, ${preferences.contrast ? '고대비' : '기본 대비'}, ${preferences.reduceMotion ? '동작 감소' : '기본 동작'}`;
}
export function showSettings() {
  showModal('접근성·조작 설정', `<div class="settings-grid"><section class="settings-section"><h3>화면 표시</h3><p>설정은 게임 점수나 법률상 판단에 영향을 주지 않습니다.</p><div class="setting-row"><div class="setting-copy"><b>글자 크기</b><span>주요 업무 텍스트를 조금 더 크게 표시합니다.</span></div><div class="segmented" role="group" aria-label="글자 크기"><button type="button" data-pref-font="standard">기본</button><button type="button" data-pref-font="large">크게</button></div></div><div class="setting-row"><div class="setting-copy"><b>고대비</b><span>텍스트와 패널 경계의 대비를 강화합니다.</span></div><button class="setting-toggle" type="button" data-pref-toggle="contrast" aria-pressed="${preferences.contrast}">${preferences.contrast ? '사용 중' : '사용 안 함'}</button></div><div class="setting-row"><div class="setting-copy"><b>애니메이션 감소</b><span>스캔·전환·알림 애니메이션을 최소화합니다.</span></div><button class="setting-toggle" type="button" data-pref-toggle="reduceMotion" aria-pressed="${preferences.reduceMotion}">${preferences.reduceMotion ? '사용 중' : '사용 안 함'}</button></div><div class="setting-row"><div class="setting-copy"><b>단축키 표시</b><span>주요 버튼 모서리에 키보드 조작 힌트를 표시합니다.</span></div><button class="setting-toggle" type="button" data-pref-toggle="shortcutHints" aria-pressed="${preferences.shortcutHints}">${preferences.shortcutHints ? '표시 중' : '숨김'}</button></div></section><section class="settings-section"><h3>키보드 단축키</h3><p>Tab / Shift+Tab과 Enter / Space는 브라우저 표준 포커스·버튼 조작을 그대로 사용합니다. 최종 결정은 오입력을 줄이기 위해 Alt 조합을 사용합니다.</p><div class="shortcut-grid">${SHORTCUT_ROWS.map(([k, v]) => `<div class="shortcut-row"><kbd>${k}</kbd><span>${v}</span></div>`).join('')}</div></section><section class="settings-section"><h3>음향·자막</h3><p>음향은 상단의 「음향」 버튼 또는 M 키로 켜고 끕니다. 음향을 꺼도 PA·운영 정보는 화면에 계속 표시됩니다.</p></section></div>`);
  const sync = () => { $$('[data-pref-font]').forEach((b) => { const on = b.dataset.prefFont === preferences.font; b.classList.toggle('on', on); b.setAttribute('aria-pressed', String(on)); }); $$('[data-pref-toggle]').forEach((b) => { const k = b.dataset.prefToggle; b.classList.toggle('on', !!preferences[k]); b.setAttribute('aria-pressed', String(!!preferences[k])); b.textContent = k === 'shortcutHints' ? (preferences[k] ? '표시 중' : '숨김') : (preferences[k] ? '사용 중' : '사용 안 함'); }); };
  $$('[data-pref-font]').forEach((b) => { b.onclick = () => { preferences.font = b.dataset.prefFont; savePreferences(); applyPreferences(); sync(); }; });
  $$('[data-pref-toggle]').forEach((b) => { b.onclick = () => { const k = b.dataset.prefToggle; preferences[k] = !preferences[k]; savePreferences(); applyPreferences(); sync(); }; });
  sync();
}
export function openRules() {
  const rules = [['입국심사 · 출입국관리법 제12조', '여권·사증, 사전여행허가, 입국목적과 체류자격의 일치, 체류기간, 제11조 입국금지·거부 대상 여부를 심사합니다. 요건을 증명하지 못하면 제4항에 따라 입국을 허가하지 않을 수 있습니다.'], ['생체정보 · 제12조의2', '면제대상이 아닌 외국인은 입국심사 때 생체정보 제공 및 본인확인 절차에 응해야 합니다. 불응 시 입국을 허가하지 않을 수 있습니다.'], ['미국·일본 일반여권', '하이코리아 공개 안내상 지정 무사증 입국허가 대상이며 90일 체류가 안내됩니다. 2026년 K-ETA 한시면제 연장 대상국은 K-ETA 없이 입국할 경우 전자입국신고 대상이 됩니다.'], ['전자입국신고', '공식 e-Arrival Card 안내상 대한민국 사증 소지자와 K-ETA 면제자는 신고 대상이고, 유효 K-ETA 소지자 및 유효 외국인등록증 등 소지자는 신고 제외 대상입니다.'], ['ABTC', '하이코리아 공개 안내상 유효 ABTC의 KOR 승인 등 요건이 충족되면 사증 없이 입국 편의가 제공되며 단기상용(C-3-4) 90일이 안내됩니다.'], ['입국불허 후 송환', '제12조제4항에 따라 입국이 허가되지 않은 사람은 제76조 송환대상이 될 수 있으며, 출국 전에는 제76조의2에 따른 출국대기실에서 대기하는 것이 원칙입니다.'], ['난민신청', '난민법 제6조에 따른 출입국항 난민신청은 회부심사를 별도로 거쳐야 합니다. 불회부 결정 자체와 입국불허는 별도 절차입니다.'], ['동행인·가족·단체여행', '같은 PNR·숙소·동행관계는 진술 교차검증을 위한 게임상 연결정보입니다. 가족·부부·친구·출장팀·단체여행이라는 사실 자체는 입국불허나 위험판정 근거가 아니며, 구성원 진술 차이가 있더라도 현재 피심사인의 입국요건을 별도로 확인합니다.'], ['업무압박 · 게임 규칙', '질문·전산조회·재심·감식 등에는 게임상 가상 처리시간이 부여됩니다. 처리속도는 법적 요건보다 우선하지 않으며, 필요한 절차를 생략하면 정확도·절차점수가 떨어지고 불필요한 재심·반복조회는 효율·비례성 점수에 반영됩니다.'], ['승객 행동·긴장 상태', '긴장도·협조도·응답상태는 대화 연출과 반복질문 피드백을 위한 게임 변수입니다. 국적·외모와 연결하지 않으며, 입국허가·입국불허·범죄혐의 판단 점수에는 사용하지 않습니다.'], ['언어·통역', '한국어·영어 능력은 개별 가상 승객의 의사소통 변수이며 입국판정 근거가 아닙니다. 직접 의사소통이 부족한 질문은 사실확인 완료로 처리되지 않습니다. 출입국사범 신문 단계에서는 출입국관리법 제48조제6항에 따라 국어가 통하지 않는 사람의 진술을 통역인에게 통역하게 하는 구조를 반영합니다.'], ['일일 미션·시나리오 프리셋', '오늘의 미션과 시나리오 프리셋은 반복 플레이를 위한 게임상 메타·운영 시스템입니다. 미션이나 프리셋은 입국요건, 법률상 정답, 국적별 지위를 변경하지 않습니다.'], ['현장 이벤트·근무 난이도', '도착편 집중, 심사대 장애, 전산조회 지연, 통역 대기, 지원심사대 등은 게임용 운영 변수입니다. 입국요건·입국불허 사유·국적별 법적 지위를 변경하지 않습니다. 훈련/표준/실전 난이도 역시 유입속도와 운영변수의 강도만 조정합니다.'], ['피로도·휴식', '피로도는 근무 메타루프와 처리시간 연출을 위한 게임 변수입니다. 법률상 판단을 자동 변경하거나 오판을 강제하지 않습니다. 근무조 전환 시 교대지원 휴식을 선택할 수 있습니다.'], ['가상화 원칙', '화면·사건번호·SIM 코드는 게임용입니다. 실제 법무부 내부 전산화면, 규제코드, 비공개 위험선별 기준을 재현하지 않습니다.']];
  showModal('업무참고 · 공개 기준', `<div class="rulegrid">${rules.map(([h, p]) => `<div class="rule"><h3>${h}</h3><p>${p}</p></div>`).join('')}</div>`, { size: 'wide' });
}
export function showHelp({ onTutorial, onRecords, onProfile, onChallenge }) {
  showModal('도움말 · 심사관 업무 안내', `<div class="help-grid"><button type="button" class="help-card" id="helpTutorial"><b>화면 안내 다시 보기</b><span>현재 승객 화면을 6단계로 다시 안내합니다.</span></button><button type="button" class="help-card" id="helpPrinciples"><b>핵심 심사 원칙</b><span>국적·태도·재심·통역·결정에 관한 핵심 원칙만 빠르게 확인합니다.</span></button><button type="button" class="help-card" id="helpRules"><b>법령·공개기준</b><span>출입국관리법·난민 절차와 공개 입국기준 참고사항을 엽니다.</span></button><button type="button" class="help-card" id="helpRecords"><b>근무기록·리플레이</b><span>자동저장, 난이도별 최고성적, 최근 근무와 사건 복기 기록을 확인합니다.</span></button><button type="button" class="help-card" id="helpProfile"><b>심사관 프로필·업적</b><span>누적 게임 경력, XP, 레벨과 해금한 업적을 확인합니다.</span></button><button type="button" class="help-card" id="helpChallenge"><b>특별 근무 도전</b><span>현재 선택한 도전의 성공조건과 진행도를 확인합니다.</span></button><button type="button" class="help-card" id="helpGuidance"><b>안내 모드</b><span>현재 모드: ${state.guidance === 'guided' ? '처음 근무' : '숙련'} · 다음 새 근무부터 시작화면에서 변경할 수 있습니다.</span></button></div>`);
  byId('helpTutorial').onclick = () => { closeModal(); onTutorial(); };
  byId('helpPrinciples').onclick = () => showModal('핵심 심사 원칙', `<div class="quick-principles"><div><b>① 먼저 입국요건.</b> 국적·외모·긴장한 태도는 위험점수가 아닙니다.</div><div><b>② 재심은 처벌이 아님.</b> 의심사항을 추가로 확인하는 제12조 입국심사의 계속입니다.</div><div><b>③ 통역은 불이익 요소가 아님.</b> 정확한 의사소통을 확보하기 위한 절차입니다.</div><div><b>④ 불회부와 입국불허는 별도.</b> 난민 회부심사 결과와 출입국관리법상 입국심사를 섞지 마십시오.</div><div><b>⑤ 결론보다 과정.</b> 필요한 질문·조회·소명 기회를 거친 뒤 처분하십시오.</div></div>`);
  byId('helpRules').onclick = openRules; byId('helpRecords').onclick = onRecords; byId('helpProfile').onclick = onProfile; byId('helpChallenge').onclick = onChallenge;
  byId('helpGuidance').onclick = () => toast('안내 모드는 새 근무 시작화면에서 변경할 수 있습니다.');
}
export function showGuidedGuard(message) { showModal('초보 심사관 보호 힌트', `<div class="guided-guard"><b>아직 결론을 내리기 이릅니다.</b><span>${esc(message)}</span></div><p class="modal-note">첫 승객에서 한 번만 제공되는 실수 방지 안내입니다. 점수·감찰에는 반영되지 않았습니다. 사건기록과 입국요건 검토판을 다시 확인하십시오.</p>`); }

// ---- Tutorial (guided mode spotlight) ---------------------------------------------------------
export const tutorial = {
  isOpen() { return byId('tutorialLayer')?.classList.contains('on'); },
  targetRect(step) { const el = document.querySelector(step.sel); if (!el) return null; const r = el.getBoundingClientRect(); return { left: Math.max(6, r.left - 5), top: Math.max(6, r.top - 5), width: Math.min(innerWidth - 12, r.width + 10), height: Math.min(innerHeight - 12, r.height + 10) }; },
  position() { const step = TUTORIAL_STEPS[state.tutorialIndex], layer = byId('tutorialLayer'); if (!layer.classList.contains('on')) return; const rr = tutorial.targetRect(step); if (!rr) return tutorial.end(false); const f = byId('tutorialFocus'), card = byId('tutorialCard'); Object.assign(f.style, { left: rr.left + 'px', top: rr.top + 'px', width: rr.width + 'px', height: rr.height + 'px' }); const cw = Math.min(400, innerWidth - 28), ch = card.offsetHeight || 190; let left = rr.left + rr.width + 14, top = rr.top; if (left + cw > innerWidth - 10) left = Math.max(10, rr.left - cw - 14); if (top + ch > innerHeight - 10) top = Math.max(10, innerHeight - ch - 10); Object.assign(card.style, { left: left + 'px', top: top + 'px' }); },
  render() { const step = TUTORIAL_STEPS[state.tutorialIndex]; byId('tutorialProgress').textContent = `화면 안내 ${state.tutorialIndex + 1} / ${TUTORIAL_STEPS.length}`; byId('tutorialTitle').textContent = step.title; byId('tutorialText').textContent = step.text; byId('tutorialLegal').textContent = step.legal; byId('tutorialPrev').disabled = state.tutorialIndex === 0; byId('tutorialNext').textContent = state.tutorialIndex === TUTORIAL_STEPS.length - 1 ? '심사 시작' : '다음'; requestAnimationFrame(tutorial.position); },
  start(force = false) { if (!state.started && !force) return; closeModal(); const l = byId('tutorialLayer'); l.classList.add('on'); l.setAttribute('aria-hidden', 'false'); state.tutorialIndex = 0; tutorial.render(); setTimeout(() => byId('tutorialNext')?.focus(), 30); },
  end(remember = true) { const l = byId('tutorialLayer'); l.classList.remove('on'); l.setAttribute('aria-hidden', 'true'); if (remember) markTutorialSeen(); },
  next() { if (state.tutorialIndex < TUTORIAL_STEPS.length - 1) { state.tutorialIndex++; tutorial.render(); } else tutorial.end(true); },
  prev() { if (state.tutorialIndex > 0) { state.tutorialIndex--; tutorial.render(); } },
  bind() { byId('tutorialNext').onclick = tutorial.next; byId('tutorialPrev').onclick = tutorial.prev; byId('tutorialSkip').onclick = () => tutorial.end(true); window.addEventListener('resize', () => { if (tutorial.isOpen()) tutorial.position(); }); }
};
