// Per-case result report, shift-transition briefing, final shift evaluation, decision documents.
import { byId, esc, fmtClock } from '../dom.js';
import { showModal, closeModal } from '../modals.js';
import { state, session } from '../../state.js';
import { current, screeningNo } from '../../engines/queue-engine.js';
import { getTraveler } from '../../engines/traveler-engine.js';
import { workloadClass, procedureAverage, overallScore, operationalScore } from '../../engines/score-engine.js';
import { difficultyCfg, scenarioCfg, simulatedBacklog, pressureInfo, shiftStats, SHIFT_TARGETS } from '../../engines/operation-engine.js';
import { languageModeLabel } from '../../engines/language-engine.js';
import { challengeCfg, challengeEvaluation } from '../../engines/achievement-engine.js';
import { campaignArc } from '../../engines/campaign-engine.js';
import { basisSectionHTML } from '../decision-basis.js';
import { ruleById } from '../../engines/decision-model.js';

// Decision document (통지서 등) with a continue button.
export function showDoc(title, rows, foot, onContinue) {
  const c = current(), t = getTraveler(c.travelerId);
  showModal(title, `<div class="report-person"><img src="${t.portrait}" alt="신원확인용 게임 보조 초상"><div class="report-person-copy"><b>${esc(t.name.korean)}</b><br>${esc(t.name.latin)}<br>${esc(t.nationality.korean)} · ${esc(screeningNo())}<br><br>※ 왼쪽 사진은 게임상 신원확인 보조패널이며 법정서식 자체의 일부가 아닙니다.</div></div><div class="docmodal"><h2>${esc(title)}</h2><table><tbody>${rows.map((r) => `<tr><th scope="row">${esc(r[0])}</th><td>${esc(r[1])}</td></tr>`).join('')}</tbody></table><p class="docmodal-foot">${esc(foot)}</p><div class="seal" aria-hidden="true">출입국·외국인정책본부<br>SIMULATION</div></div><button type="button" class="act clear block" id="docContinue"><strong>확인</strong></button>`);
  byId('docContinue').onclick = () => { closeModal(); onContinue && onContinue(); };
}

export function showCaseResult(r, onNext) {
  const { c, t, label, seconds, procedure, effEval, caseEff, last, pressure, backlog, clue, party, challenge, storyResult } = r; const timeClass = caseEff >= 90 ? 'good' : caseEff >= 75 ? 'warn' : 'bad';
  showModal('심사 처리 결과', `<div class="report-person"><img src="${t.portrait}" alt=""><div><div class="report-name">${esc(t.name.korean)}</div><div class="report-sub mono">${esc(t.name.latin)} · ${esc(t.nationality.korean)}</div><div class="report"><div class="r"><span>최종결정</span><b>${esc(label)}</b></div><div class="r"><span>절차 준수</span><b>${procedure}%</b></div><div class="r"><span>조회·질문</span><b>${state.asked.size + state.looked.size}</b></div><div class="r"><span>가상 처리시간</span><b>${fmtClock(seconds)}</b></div></div></div></div><div class="balance-strip"><div class="balance-chip ${workloadClass(state.score)}"><span>법률 정확도</span><b>${state.score}</b></div><div class="balance-chip ${workloadClass(procedureAverage())}"><span>절차 준수</span><b>${procedureAverage()}</b></div><div class="balance-chip ${workloadClass(state.efficiency)}"><span>처리 효율</span><b>${state.efficiency}</b></div><div class="balance-chip ${workloadClass(state.proportionality)}"><span>업무 비례성</span><b>${state.proportionality}</b></div></div><div class="workload-note ${timeClass}"><b>업무량 평가</b> · 기준 ${effEval.ideal}초 / 실제 ${seconds}초 · 현재 대기 ${backlog}명 (${pressure[0]})${effEval.delta < 0 ? ` · 처리효율 ${effEval.delta}점` : effEval.delta > 0 ? ' · 적정 처리속도' : ''}</div><div class="interaction-report"><b>상호작용 기록</b> · 종료 시 긴장도 ${state.behavior?.stress ?? 0} / 협조도 ${state.behavior?.rapport ?? 0} · 재질문 ${state.behavior?.repeatCount ?? 0}회<br><b>근무상태</b> · 난이도 ${difficultyCfg().label} · 피로도 ${Math.round(state.fatigue)} · 현장 이벤트 ${state.eventsSeen}회<br><b>언어 지원</b> · ${esc(languageModeLabel())}${state.language?.interpreterUsed ? ` · ${esc(state.language.primary)} 통역 사용 · 통역 질문 ${state.language.assistedTurns}회` : ' · 통역 미사용'}<br>승객 행동·언어능력은 대화 UX 변수이며 입국판정·법률점수에는 반영되지 않습니다.${party ? `<br><b>동행여행</b> · ${esc(party.label)} ${party.members.length}명 · 공동 PNR ${esc(party.sharedPNR)} · 동행 여부 자체는 판정근거 아님` : ''}</div>${clue ? `<div class="report-depth"><b>단서 확보</b> · 핵심 ${clue.keyGot.length}/${clue.keys.length} · 전체 ${clue.got.length}/${clue.all.length}<br>핵심 단서를 모두 보지 않아도 처분은 가능할 수 있으나, 성급한 판단은 절차·정확도 평가에 반영됩니다.</div>` : ''}${basisSectionHTML(c, state)}<p class="modal-note"><b>사건 해설</b> · ${esc(c.note)}</p>${challenge ? `<div class="challenge-result"><b>도전 진행 · ${esc(challenge.cfg.name)} ${challenge.eval.pct}%</b><span>${esc(challenge.eval.detail)}</span></div>` : ''}${storyResult ? `<div class="story-report"><b>캠페인 연계사건</b> · ${esc(storyResult.title)}<br>${esc(storyResult.summary)}<br>이 평가는 서사 복기용이며 현재 승객의 법률상 결론을 변경하지 않습니다.</div>` : ''}<button type="button" class="act clear block" id="nextCase"><strong>${last ? '근무평정 보기' : '다음 승객 호출'}</strong></button>`);
  byId('nextCase').onclick = () => { closeModal(); onNext(); };
}

export function showShiftTransition(sh, { onBegin, onBreak }) {
  const title = sh === 2 ? '제2근무조 · 재심 및 목적 확인' : '제3근무조 · 특수사건'; const preview = session.queue.slice(state.caseIndex, state.caseIndex + 8).map((q) => getTraveler(q.travelerId)); const prev = shiftStats(sh - 1), target = SHIFT_TARGETS[sh];
  showModal('근무조 전환', `<h3>${title}</h3><div class="shift-target"><span>직전 근무조 평균</span><b>${prev.avg}s · ${prev.status}</b><span>새 근무조 목표 평균</span><b>${target.avg}s</b></div><div class="duty-grid"><div class="duty-cell"><span>현재 대기</span><b>${simulatedBacklog()}</b></div><div class="duty-cell"><span>피로도</span><b>${Math.round(state.fatigue)}</b></div><div class="duty-cell"><span>현장 이벤트</span><b>${state.eventsSeen}</b></div><div class="duty-cell"><span>운영 안정성</span><b>${operationalScore()}</b></div></div><p class="modal-note">특수·재심 사건은 시간이 더 필요한 것이 정상입니다. 속도를 이유로 필요한 확인을 생략하지 마십시오. 교대지원 휴식은 피로도를 낮추지만 대기열이 소폭 증가합니다.</p><div class="briefpeople">${preview.map((t) => `<img src="${t.portrait}" alt="">`).join('')}</div><div class="break-choice"><button type="button" class="break-btn" id="takeBreak"><b>교대지원 휴식 10분</b><small>피로도 -30 · 대기 +2명</small></button><button type="button" class="act clear" id="beginShift"><strong>바로 심사 계속</strong></button></div>`);
  byId('beginShift').onclick = () => { closeModal(); onBegin(); }; byId('takeBreak').onclick = () => { closeModal(); onBreak(); };
  return title;
}

export function showShiftComplete(r, { onProfile, onRecords, onRestart }) {
  const { grade, avg, procedure, overall, ops, challengeFinal, challengeNow, newly, featured, campaignResult } = r; const ss = [1, 2, 3].map(shiftStats);
  const rows = [['처리 인원', state.stats.processed], ['입국 허가', state.stats.admitted], ['재심 인계', state.stats.secondary], ['입국 불허', state.stats.refused], ['난민신청', state.stats.refugee], ['사범조사', state.stats.investigation], ['통역 호출', state.stats.interpreter], ['난이도', difficultyCfg().label], ['현장 이벤트', state.eventsSeen], ['휴식', state.breaksTaken], ['최고 피로도', Math.round(state.peakFatigue)], ['평균 처리시간', fmtClock(avg)], ['최고 대기인원', state.pressurePeak], ['과잉재심', state.overSecondary], ['반복질문', state.repeatedQuestions], ['종합평가', overall]];
  let campaignBox = '';
  if (campaignResult) { const cr = campaignResult; campaignBox = `<div class="campaign-final ${cr.failed ? 'fail' : ''}">${cr.completed ? `<b>3일 캠페인 완주 · ${esc(cr.cfg.name)}</b><span>총 108명 연속근무 완료 · 완주 보너스 +${cr.bonusXP} XP${cr.perfect ? ' · 3일 전부 S등급 완벽완주' : ''}</span>` : cr.failed ? `<b>캠페인 중단 · ${esc(cr.cfg.name)}</b><span>DAY ${cr.res.day} 근무가 F등급으로 종료되어 연속 캠페인이 종료되었습니다.</span>` : `<b>DAY ${cr.res.day}/3 완료 · 다음 근무 준비</b><span>${esc(cr.carry.label)} · 다음 DAY 시작 대기 ${cr.carry.backlog >= 0 ? '+' : ''}${cr.carry.backlog} · 시작 피로 ${cr.carry.fatigue}. 법률상 정답은 변하지 않습니다.</span>`}</div>`; const arc = campaignArc(), story = cr.c?.story; if (arc && story) { const done = arc.chapters.filter((_, i) => story.chapters?.[i]?.status === 'complete').length; campaignBox += `<div class="story-report"><b>연계사건 완성도 ${done}/3</b><br>${esc(arc.title)} · ${done === 3 ? '3일 연계기록을 모두 원자료 기반으로 정리했습니다.' : '일부 연계기록은 미완료 상태로 남았습니다.'}<br>서사 완성도는 캠페인 XP·법률점수에 영향을 주지 않습니다.</div>`; } }
  const restartLabel = campaignResult && !campaignResult.completed && !campaignResult.failed ? `DAY ${campaignResult.res.day + 1} 시작화면` : '새 근무';
  showModal('근무 종료 · 종합 근무평정', `<div class="biggrade">${grade}</div><div class="grade-seed"><span class="seed-badge">SESSION ${session.seed}</span></div><div class="balance-strip final-balance"><div class="balance-chip ${workloadClass(state.score)}"><span>법률 정확도</span><b>${state.score}</b></div><div class="balance-chip ${workloadClass(procedure)}"><span>절차 준수율</span><b>${procedure}</b></div><div class="balance-chip ${workloadClass(state.efficiency)}"><span>처리 효율</span><b>${state.efficiency}</b></div><div class="balance-chip ${workloadClass(state.proportionality)}"><span>업무 비례성</span><b>${state.proportionality}</b></div><div class="balance-chip ${workloadClass(ops)}"><span>운영 안정성</span><b>${ops}</b></div></div><div class="report">${rows.map(([k, v]) => `<div class="r"><span>${k}</span><b>${v}</b></div>`).join('')}</div><div class="shift-target">${ss.map((s, i) => `<span>제${i + 1}근무조 · ${SHIFT_TARGETS[i + 1].label}</span><b class="${s.avg <= s.target ? '정상' : s.avg <= s.target * 1.2 ? '주의' : '경고'}">${s.avg}s / 목표 ${s.target}s</b>`).join('')}</div><div class="event-detail-card"><h3>현장 운영 요약</h3><p>난이도 ${difficultyCfg().label} · 시나리오 ${esc(scenarioCfg().name)} · 현장 이벤트 ${state.eventsSeen}회 · 교대지원 휴식 ${state.breaksTaken}회 · 최고 피로도 ${Math.round(state.peakFatigue)} · 운영 안정성 ${ops}</p></div>${challengeNow.id !== 'none' ? `<div class="challenge-result ${challengeFinal.success ? 'success' : 'fail'}"><b>${challengeFinal.success ? '특별 근무 도전 성공' : '특별 근무 도전 미달'} · ${esc(challengeNow.name)}</b><span>${esc(challengeFinal.detail)}</span><strong>${challengeFinal.success ? `보너스 +${challengeNow.bonus} XP 지급` : 'XP 보너스 없음'}</strong></div>` : ''}<div class="briefpeople">${featured.map((x) => `<img src="${getTraveler(x.travelerId).portrait}" title="${esc(x.screening)} · ${esc(x.label)}" alt="">`).join('')}</div>${state.newDailyRewards.length ? `<div class="daily-reward-strip"><b>오늘의 미션 보상</b><span>${state.newDailyRewards.map((x) => `${esc(x.name)} +${x.xp} XP`).join(' · ')}</span></div>` : ''}${newly.length ? `<div class="unlock-strip"><b>새 업적 해금</b><div class="new-achievements">${newly.map((a) => `<span class="new-achievement">${esc(a.icon)} · ${esc(a.name)}</span>`).join('')}</div></div>` : ''}<p class="grade-note">${grade === 'S' ? '최우수 근무평정 · 정확성, 절차, 처리속도와 조치의 비례성을 모두 유지했습니다.' : '판정 정확성뿐 아니라 과잉조치와 처리지연도 함께 점검하십시오.'}</p>${campaignBox}<div class="final-actions"><button type="button" class="act secondary" id="finalProfile"><strong>프로필·업적</strong></button><button type="button" class="act secondary" id="finalRecords"><strong>근무기록</strong></button><button type="button" class="act clear" id="restart"><strong>${restartLabel}</strong></button></div>`, { size: 'wide' });
  byId('finalProfile').onclick = onProfile; byId('finalRecords').onclick = onRecords; byId('restart').onclick = onRestart;
}
export function showGameOver(onRestart) { showModal('감찰 누적 3회 · 근무 종료', `<div class="biggrade danger">F</div><p class="grade-note">게임상 징계위원회 파면 엔딩입니다.<br><small>실제 개별 징계결과를 의미하지 않는 가상 연출입니다.</small></p><button type="button" class="act refuse block" id="restart"><strong>다시 시작</strong></button>`); byId('restart').onclick = onRestart; }
export function showFatalAbuse(onRestart) { showModal('치명적 절차위반', `<div class="fatal-box"><h3>FATAL PROCEDURAL ABUSE</h3><p>긴급체포 요건을 모두 확인하지 않고 체포를 집행했습니다. 형법 제124조상 불법체포·불법감금 등 위법성 검토와 감찰 절차가 개시되는 게임오버 상황입니다.</p></div><button type="button" class="act refuse block" id="restart"><strong>근무 재시작</strong></button>`); byId('restart').onclick = onRestart; }
export function showRefusalReasons(reasons, onPick) { showModal('입국 불허가 사유 선택 · 출입국관리법 제12조제4항', `<p class="modal-note">제12조제3항 각 호의 요건을 갖추었음을 증명하지 못한 경우 입국을 허가하지 아니할 수 있습니다(제4항). 사유는 사실관계와 법정 요건에 맞게 선택하십시오.</p><div class="reasons">${reasons.map((r) => `<button type="button" class="reason" data-code="${r[0]}"><strong>${r[1]}</strong><span>${r[2]}<br>${r[0]} · SIMULATION CODE</span></button>`).join('')}</div><details class="basis-node"><summary><span class="basis-domain">근거 조문 안내</span><span class="basis-summary">제12조제4항 · 제12조의2제2항 · 제11조 · 제76조</span></summary><div class="basis-body"><p class="modal-note">${esc(ruleById('R-12-4-BURDEN').explanation)} ${esc(ruleById('R-11-BAN').explanation)} 불허가 후에는 ${esc(ruleById('R-76-REPAT').title)} 절차로 이어집니다.</p></div></details><p class="modal-note">SIM 코드는 실제 법무부 내부 분류코드가 아닙니다.</p>`); document.querySelectorAll('.reason').forEach((b) => { b.onclick = () => onPick(b.dataset.code); }); }
