// Labelled examiner utterances for the intent engine (Korean, English, mixed, typos, speech-style).
// expect: a question id of the case, or 'meta:<INTENT>', 'doc:<KEY>', 'unknown'. Used by tests/unit/dialogue.test.js
// and scripts/eval-dialogue.js. Add a line whenever a playtest shows a mis-route.
export const INTENT_CASES = {
  'ICN-S2-005': [
    ['한국에서 30일 동안 뭐 할 거예요?', 'purpose'],
    ['방문 목적이 뭡니까', 'purpose'],
    ['무슨 일로 오셨어요?', 'purpose'],
    ['What will you do in Korea for a month?', 'purpose'],
    ['what is the purpose of your visit', 'purpose'],
    ['관광 말고 다른 계획 있어요?', 'purpose'],
    ['돌아가는 비행기표는 왜 없어요?', 'return'],
    ['귀국 항공권 있습니까', 'return'],
    ['언제 베트남으로 돌아가요', 'return'],
    ["Why don't you have a return ticket?", 'return'],
    ['do you have a flight home', 'return'],
    ['돈은 얼마나 가지고 왔어요?', 'funds'],
    ['체재비 있어요? 카드는요?', 'funds'],
    ['현금 얼마 있습니까', 'funds'],
    ['How much money do you have?', 'funds'],
    ['can you afford a month here', 'funds'],
    ['010-0000-0202 이 번호 누구 거예요?', 'contact'],
    ['국내 연락처는 누구입니까', 'contact'],
    ['입국신고서에 적은 전화번호는 누구 번호죠', 'contact'],
    ['Who is the contact number on your form?', 'contact'],
    ['휴대폰 좀 보여주실 수 있어요?', 'phone'],
    ['핸드폰에 있는 예약 내역 보여줄 수 있나요', 'phone'],
    ['Can I see your phone?', 'phone'],
    ['베트남에서 무슨 일 하세요?', 'occupation'],
    ['직업이 뭐예요', 'occupation'],
    ['수입은 어떻게 돼요? 회사 다녀요?', 'occupation'],
    ['What do you do for a living?', 'occupation'],
    ['what is your job in vietnam', 'occupation'],
    ['구로구 그 집에는 누가 살아요?', 'addressOwner'],
    ['신고한 주택 거주자가 누구입니까', 'addressOwner'],
    ['Who lives at the house in Guro?', 'addressOwner'],
    ['한국에서 일자리 알아본 적 있어요?', 'jobOffer'],
    ['여기서 일할 생각이에요?', 'jobOffer'],
    ['공장에서 일하려고 온 거 아니에요?', 'jobOffer'],
    ['Are you planning to work in Korea?', 'jobOffer'],
    ['have you looked for a job here', 'jobOffer'],
    ['연락처 조회해 보니 취업 알선 번호로 나오던데, 일하러 온 거죠?', 'jobOffer'],
    ['귀국 항공권은 나중에 무슨 돈으로 살 거예요?', 'returnMoney'],
    ['돌아가는 표 살 돈은 어떻게 마련해요', 'returnMoney'],
    ['How will you pay for the ticket home later?', 'returnMoney'],
    ['그 연락처 사람은 어떻게 알게 됐어요?', 'host'],
    ['그 사람이랑 처음에 어떻게 알게 되었나요', 'host'],
    ['How did you meet your contact?', 'host'],
    ['안녕하세요', 'meta:GREETING'],
    ['Hello there', 'meta:GREETING'],
    ['베트남어 통역 불러 드릴게요', 'meta:INTERPRETER'],
    ['I will call an interpreter', 'meta:INTERPRETER'],
    ['영어로 말해도 될까요?', 'meta:LANG_EN'],
    ['감사합니다', 'meta:THANKS'],
    ['다시 말씀해 주시겠어요?', 'meta:REPEAT'],
    ['여권 보여주세요', 'doc:PASSPORT'],
    ['비자 좀 볼 수 있을까요', 'doc:VISA'],
    ['좋아하는 음식이 뭐예요?', 'unknown'],
    ['오늘 날씨 좋네요', 'unknown'],
    ['asdf qwer', 'unknown'],
    // playtest 2026-10-02 (informal speech, spacing) — added after the persona run, so tuned data
    ['왜 한국 왔어?', 'purpose'],
    ['한 달이나 있으면서 일정이 없어?', 'purpose'],
    ['집 주인 누구야', 'addressOwner'],
    ['베트남에선 뭐 했는데', 'occupation'],
    ['폰 좀 보자', 'phone'],
    ['너 혹시 일하러 왔지?', 'jobOffer'],
    ['그 사람 어떻게 알아', 'host']
  ],
  // Held-out round 1 (written after the first tuning pass): 13/18 on first run; its misses were then fixed,
  // so it is training data now. Round 2 below is the current held-out set.
  'ICN-S2-005#round1': [
    ['한 달이나 있으면서 관광 일정이 하나도 없어요?', 'purpose'],
    ['Tell me your plans for the next thirty days', 'purpose'],
    ['편도로만 끊으셨네요. 왜죠?', 'return'],
    ['When are you leaving Korea?', 'return'],
    ['한 달 지낼 돈이 15만원이면 충분하다고 생각하세요?', 'funds'],
    ['카드 한도는 얼마예요?', 'funds'],
    ['여기 적힌 번호의 주인은 누구죠?', 'contact'],
    ['휴대전화로 예약 확인 좀 해 주시겠어요?', 'phone'],
    ['요즘 무슨 일 하고 지내세요?', 'occupation'],
    ['Are you working right now back home?', 'occupation'],
    ['구로 집은 누구 집이에요?', 'addressOwner'],
    ['한국에서 돈 벌 계획 있으세요?', 'jobOffer'],
    ['Did anyone offer you work here?', 'jobOffer'],
    ['나중에 표 살 돈은 어디서 나요?', 'returnMoney'],
    ['그 친구의 친구는 어디서 소개받았어요?', 'host'],
    ['혹시 축구 좋아하세요?', 'unknown'],
    ['I like your jacket', 'unknown'],
    ['서울은 처음이세요?', 'unknown']
  ],
  'ICN-S2-006': [
    ['호텔 예약자가 왜 본인이 아니죠?', 'hotel'],
    ['같이 온 친구 이름이 뭐예요?', 'friend'],
    ['귀국 항공권 보여 주세요', 'return'],
    ['여행 경비는 어떻게 준비했어요', 'funds'],
    ['예약 확인서 대표 예약자가 누구예요', 'bookingName'],
    ['본인 돈도 따로 있어요?', 'separateFunds'],
    ['서울이랑 부산은 어떻게 이동해요?', 'itinerary'],
    ['한국에서 일할 계획 있어요?', 'work'],
    ['Who booked the hotel?', 'bookingName'],
    ['Do you plan to work here?', 'work']
  ],
  'ICN-S1-001': [
    ['방문 목적이 뭐예요', 'purpose'],
    ['어디서 묵으세요?', 'hotel'],
    ['귀국편은 언제죠', 'return'],
    ['경비는 충분해요?', 'funds'],
    ['컨퍼런스 일정 말해 주세요', 'agenda'],
    ['한국 회사에서 돈 받아요?', 'pay'],
    ['짐에 샘플 있어요?', 'samples'],
    ['항공권이랑 숙박비는 누가 내요?', 'sponsor'],
    ['Where are you staying?', 'hotel'],
    ['Who pays for your trip?', 'sponsor']
  ],
  // Held-out round 2: written before any run against it. Do not tune the lexicon on it; record its score
  // in docs/v10-qa.md and write round 3 when it is used up.
  'ICN-S2-005#heldout2': [
    ['관광지는 어디 어디 가 보실 거예요?', 'purpose'],
    ['So what brings you to Seoul?', 'purpose'],
    ['돌아갈 날짜는 정해졌어요?', 'return'],
    ['No return flight booked?', 'return'],
    ['생활비는 어떻게 쓰실 생각이세요?', 'funds'],
    ['Do you have enough cash for thirty days?', 'funds'],
    ['신고서에 쓴 연락처 분은 어떤 분이세요?', 'contact'],
    ['폰 좀 확인해도 될까요?', 'phone'],
    ['베트남에서는 어떤 일을 하셨어요?', 'occupation'],
    ['What was your last job?', 'occupation'],
    ['그 주택에 누가 사는지 아세요?', 'addressOwner'],
    ['혹시 한국에서 일하실 생각 있으세요?', 'jobOffer'],
    ['Is someone giving you a job in Korea?', 'jobOffer'],
    ['표 살 돈은 지금 없는 거죠? 나중에 어떻게 사요?', 'returnMoney'],
    ['그 분이랑은 어떻게 연락하게 됐어요?', 'host'],
    ['배고프지 않으세요?', 'unknown'],
    ['What time is it?', 'unknown']
  ],
  // Round 3 (pilot cases): first run 17/24 (70.8 %, 2 wrong routes; ICN-S3-011 2/8 — no age/official/exemption/consent
  // concepts). Used for tuning afterwards, so it is training data now; round 4 below is the held-out set.
  'ICN-S1-002#round3': [
    ['이번에 한국 온 목적이 뭐예요?', 'purpose'],
    ['어느 호텔에 묵으세요?', 'hotel'],
    ['일본에는 언제 돌아가요?', 'return'],
    ['같이 온 친구는 누구예요?', 'companion'],
    ['한국에 아는 사람 만날 거예요?', 'friendKorea'],
    ['여행 경비는 어떻게 준비했어요?', 'budget'],
    ['Are you going to study in Korea?', 'study'],
    ['좋아하는 한국 음식 있어요?', 'unknown']
  ],
  'ICN-S3-010#round3': [
    ['어디서 지내실 거예요? 일정은요?', 'purpose'],
    ['돈은 얼마나 있어요?', 'funds'],
    ['돌아가면 위험하다는 뜻인가요?', 'refugee'],
    ['누가 왜 해를 끼친다는 거죠?', 'persecution'],
    ['가족은 지금 이집트에 있어요?', 'family'],
    ['다른 나라에서 보호 요청한 적 있어요?', 'route'],
    ['한국에서 무슨 일을 하고 싶었어요?', 'workPlan'],
    ['난민 신청은 언제부터 생각했어요?', 'claimTiming']
  ],
  'ICN-S3-011#round3': [
    ['지문 찍는 거 하실 거죠?', 'bio'],
    ['면제받을 이유가 있나요?', 'exempt'],
    ['나이가 17세 미만이에요?', 'age'],
    ['정부 공무로 오셨어요?', 'official'],
    ['안내 들으셨죠, 이제 응하시겠어요?', 'explain'],
    ['다른 서류는 다 괜찮은데 생체정보만 거부하시는 거죠?', 'otherDocs'],
    ['Will you give your fingerprints?', 'bio'],
    ['사촌은 어디 살아요?', 'unknown']
  ],
  // Held-out round 4 (written before any run against it, after the round-3 tuning). Do not tune on it.
  'ICN-S3-011#heldout4': [
    ['얼굴 사진이랑 지문 등록 절차 진행해도 될까요?', 'bio'],
    ['혹시 생체정보를 안 해도 되는 사유가 있으세요?', 'exempt'],
    ['미성년자는 아니시죠?', 'age'],
    ['외교관이나 국제기구 업무로 오신 건가요?', 'official'],
    ['설명 들으셨으니 지금이라도 협조하시겠어요?', 'explain']
  ],
  'ICN-S1-001#heldout4': [
    ['출장 오신 거죠? 무슨 일로요?', 'purpose'],
    ['미팅 일정은 어떻게 돼요?', 'agenda'],
    ['한국 회사가 돈 주나요?', 'pay'],
    ['짐에 판매용 물건 있어요?', 'samples'],
    ['출장비는 회사가 내요?', 'sponsor']
  ],
  'ICN-S2-006#heldout4': [
    ['왜 친구 이름으로 예약돼 있어요?', 'hotel'],
    ['같이 온 분 이름이 뭐예요?', 'friend'],
    ['부산은 언제 가요?', 'itinerary'],
    ['본인 카드도 따로 있어요?', 'separateFunds'],
    ['여기서 돈 벌 생각 있어요?', 'work']
  ],
  // Round 5 (2026-10-02, the six cases that had no persona; written before any run against them). Case of the Day
  // draws from all twelve cases. First run 20/37 (54.1 %, 2 wrong routes, 15 not placed); used for tuning afterwards,
  // so it is training data now. Round 6 below is the held-out set for these cases.
  'ICN-S1-003#round5': [
    ['외국인등록증 좀 보여주세요', 'residence'],
    ['지금 어디 사세요?', 'address'],
    ['체류기간 언제까지예요?', 'expiry'],
    ['캐나다는 왜 다녀오셨어요?', 'trip'],
    ['한국에서 무슨 일 하세요?', 'job'],
    ['Why no K-ETA?', 'keta']
  ],
  'ICN-S1-004#round5': [
    ['ABTC 카드랑 여권 정보 같아요?', 'abtc'],
    ['어느 회사 만나러 오셨어요?', 'business'],
    ['언제 출국하세요?', 'return'],
    ['미팅 담당자가 누구예요?', 'agenda'],
    ['한국 회사에서 돈 받아요?', 'pay'],
    ['Do you have product samples with you?', 'samples']
  ],
  'ICN-S2-007#round5': [
    ['호텔 예약한 거 있어요?', 'hotel'],
    ['같이 온 친구 이름이 뭐예요?', 'friend'],
    ['필리핀에서는 무슨 일 해요?', 'work'],
    ['돈 얼마 가져왔어요?', 'funds'],
    ['마사지샵에서 뭘 도와준다는 거예요?', 'massage'],
    ['Alex는 어떻게 알게 됐어요?', 'alex'],
    ['한국에서 지내는 비용은 누가 내요?', 'sponsor']
  ],
  'ICN-S2-008#round5': [
    ['초청한 회사가 어디예요?', 'company'],
    ['한국에서 직접 일하세요?', 'purpose'],
    ['초청장 보여주세요', 'invite'],
    ['검수할 때 직접 조립하거나 수리해요?', 'inspection'],
    ['공구 가져왔어요?', 'tools'],
    ['What is your schedule for the six days?', 'schedule']
  ],
  'ICN-S3-009#round5': [
    ['본명이 뭐예요?', 'identity'],
    ['어디 거쳐서 왔어요?', 'route'],
    ['예약 화면 보여줄 수 있어요?', 'phone'],
    ['이 여권 어디서 받았어요?', 'purchase'],
    ['같은 예약에 있는 사람 알아요?', 'companion'],
    ['메시지 왜 지우려고 했어요?', 'destroy']
  ],
  'ICN-S3-012#round5': [
    ['예전에 한국에서 추방된 적 있어요?', 'history'],
    ['관광 목적 맞아요?', 'purpose'],
    ['그때 언제 출국했어요?', 'date'],
    ['입국 금지 풀렸다는 통지 받았어요?', 'permission'],
    ['호텔이랑 귀국편 예약했어요?', 'hotel'],
    ['Did you know it was a deportation order?', 'order']
  ],
  // Held-out round 6 (written after the round-5 tuning, before any run against it). Do not tune on it.
  'ICN-S1-003#heldout6': [
    ['등록증 갖고 계세요?', 'residence'],
    ['한국 주소가 바뀐 건 없죠?', 'address'],
    ['등록증 유효기간 좀 볼게요', 'expiry'],
    ['What were you doing in Canada?', 'trip'],
    ['회사 다니세요?', 'job']
  ],
  'ICN-S1-004#heldout6': [
    ['ABTC에 한국 승인 들어가 있어요?', 'kor'],
    ['돌아가는 날이 언제예요?', 'return'],
    ['거래처랑 무슨 업무 하세요?', 'business'],
    ['Will you do any paid work for the Korean company?', 'pay'],
    ['미팅 스케줄이 어떻게 돼요?', 'agenda']
  ],
  'ICN-S2-007#heldout6': [
    ['호텔 이름이 정확히 뭐예요?', 'hotelName'],
    ['Alex랑은 무슨 사이예요?', 'alex'],
    ['한국에서 일할 거예요?', 'massage'],
    ['비행기표대로 돌아갈 거예요?', 'returnPlan'],
    ['How much cash do you have?', 'funds']
  ],
  'ICN-S2-008#heldout6': [
    ['담당자 이름이 뭐예요?', 'company'],
    ['한국 회사에서 급여 받으세요?', 'pay'],
    ['공장에서 설비 설치하세요?', 'inspection'],
    ['측정 장비 같은 거 가져왔어요?', 'tools'],
    ['언제 어디 방문하는지 일정 말해 주세요', 'schedule']
  ],
  'ICN-S3-009#heldout6': [
    ['다른 이름 쓴 적 있어요?', 'trueName'],
    ['환승은 어디서 했어요?', 'route'],
    ['여권 누구한테 샀어요?', 'purchase'],
    ['새 이름으로 통과라는 문자 무슨 뜻이에요?', 'messages'],
    ['Are you really a German citizen?', 'identity']
  ],
  'ICN-S3-012#heldout6': [
    ['한국에서 강제퇴거 당한 적 있죠?', 'history'],
    ['출국명령이랑 강제퇴거 차이 알았어요?', 'order'],
    ['재입국 허가 받은 적 있어요?', 'permission'],
    ['며칠 있다 가세요?', 'purpose'],
    ['When did you leave Korea last time?', 'date']
  ],
  // Held-out round 7: large realistic corpus expansion (≥300 total utterances across short, polite, blunt, typos, English, mixed, out-of-scope).
  'ICN-S2-005#heldout7': [
    ['일 뭐해요?', 'occupation'],
    ['직업이?', 'occupation'],
    ['돈 얼마 있어요?', 'funds'],
    ['표 왜 없어?', 'return'],
    ['폰 줘봐요', 'phone'],
    ['구로 집 누구 거예요?', 'addressOwner'],
    ['그 사람 누구예요?', 'contact'],
    ['왜 왔어요?', 'purpose'],
    ['돈 벌러 왔지?', 'jobOffer'],
    ['누구네 집이에요?', 'addressOwner'],
    ['혹시 체재 경비는 어느 정도 소지하고 계십니까?', 'funds'],
    ['귀국 일정에 대해 구체적으로 말씀해 주시겠습니까?', 'return'],
    ['금번 방문 목적을 상세히 설명해 주십시오.', 'purpose'],
    ['본국에서 하는 주요 업무와 소득에 대해 말씀해 주십시오.', 'occupation'],
    ['신고서에 기재하신 주소지의 거주자는 귀하와 어떤 관계입니까?', 'addressOwner'],
    ['차후 귀국 항공권을 발권할 자금은 어떻게 조달할 예정입니까?', 'returnMoney'],
    ['돈 얼마 있어', 'funds'],
    ['표 왜 없어', 'return'],
    ['여기서 돈 벌려고 왔지?', 'jobOffer'],
    ['누구 집이야', 'addressOwner'],
    ['직업 뭐야', 'occupation'],
    ['폰 줘봐', 'phone'],
    ['한국에 일하러 왓어요?', 'jobOffer'],
    ['귀국 뱅기표 잇어요?', 'return'],
    ['돈 얼마나 잇나요', 'funds'],
    ['왜왓어요', 'purpose'],
    ['How much cash do you have on you?', 'funds'],
    ['Show me your phone, please.', 'phone'],
    ['Why do you have no return ticket?', 'return'],
    ['What is your occupation back home?', 'occupation'],
    ['Who lives in that house?', 'addressOwner'],
    ['Did someone offer you a job here?', 'jobOffer'],
    ['리턴 티켓 확인 가능한가요?', 'return'],
    ['스마트폰 예약 내역 보여주세요', 'phone'],
    ['캐시 얼마나 들고 왔어요?', 'funds'],
    ['오늘 날씨 참 춥네요', 'unknown'],
    ['점심 메뉴 추천해 드릴까요?', 'unknown'],
    ['한국 축구 대표팀 경기 보셨어요?', 'unknown'],
    ['어디서 식사하셨어요?', 'unknown'],
    ['what is the capital of france', 'unknown'],
    ['xyz 98765 abcd', 'unknown']
  ],
  'ICN-S2-006#heldout7': [
    ['혼자 왔어요?', 'friend'],
    ['친구랑 왔어요?', 'friend'],
    ['호텔 예약자 누구예요?', 'bookingName'],
    ['왜 친구 이름으로 예약했어요?', 'hotel'],
    ['카드도 따로 있어요?', 'separateFunds'],
    ['서울 말고 다른 데도 가요?', 'itinerary'],
    ['여기서 일 구해요?', 'work'],
    ['친구는 어디 있어요?', 'friend'],
    ['부산 언제가요?', 'itinerary'],
    ['경비는 각자 내요?', 'separateFunds'],
    ['Is your friend travelling with you?', 'friend'],
    ['Who paid for this hotel reservation?', 'bookingName'],
    ['Do you have your own credit card?', 'separateFunds'],
    ['Are you looking for employment in Korea?', 'work'],
    ['인천공항 시설 깨끗하죠?', 'unknown'],
    ['오늘 몇 시 비행기였어요?', 'unknown']
  ],
  'ICN-S1-001#heldout7': [
    ['컨퍼런스 발표 언제예요?', 'agenda'],
    ['한국 거래처에서 돈 받아요?', 'pay'],
    ['가방 안에 샘플 물품 있어요?', 'samples'],
    ['호텔 어디로 예약하셨어요?', 'hotel'],
    ['언제 다시 미국 돌아가세요?', 'return'],
    ['출장 경비는 넉넉하세요?', 'funds'],
    ['Are you receiving any compensation from the Korean host?', 'pay'],
    ['Do you carry any commercial goods or samples?', 'samples'],
    ['Who is funding your travel and accommodation?', 'sponsor']
  ],
  'ICN-S3-009#heldout7': [
    ['진짜 이름이 뭐예요?', 'identity'],
    ['이 여권 본인 거 맞아요?', 'identity'],
    ['다른 신분 사용한 적 있습니까?', 'trueName'],
    ['여권 어디서 구입했어요?', 'purchase'],
    ['메시지는 왜 지웠어요?', 'destroy'],
    ['어느 나라 거쳐서 왔어요?', 'route'],
    ['Did you buy this passport from someone?', 'purchase'],
    ['Why did you try to wipe your messages?', 'destroy'],
    ['What transit airports did you use?', 'route'],
    ['Have you ever held a different identity?', 'trueName']
  ],
  'ICN-S3-011#heldout7': [
    ['법적 불이익 안내해 드렸는데, 지금이라도 지문 등록에 응하시겠어요?', 'explain'],
    ['생체정보 등록 면제 대상이신가요?', 'exempt'],
    ['외교관 여권 소지자이십니까?', 'official'],
    ['나이가 17세 미만이세요?', 'age'],
    ['여권이랑 다른 서류는 모두 이상 없으신가요?', 'otherDocs'],
    ['Now that consequences were explained, will you cooperate?', 'explain'],
    ['Are you on official diplomatic duty?', 'official']
  ]
};
