#!/usr/bin/env python3
"""Offline, build-time tool: derive a tiny 2.5D 'rig' (eye, brow, mouth, jaw anchors) for every portrait.

The runtime avatar (src/js/ui/avatar/) animates the existing still portraits (blink, breathing, jaw motion,
head micro-motion) with these anchors. Landmarks are computed once on the developer's machine with
MediaPipe Face Mesh (pip `mediapipe==0.10.14`, which bundles its model) and written as normalised
coordinates to src/data/portrait-rigs.js. Nothing here runs in the browser and no image leaves the machine.

usage: python3 scripts/extract-portrait-rigs.py
"""
import json, os, sys, glob
import numpy as np
import cv2
import mediapipe as mp

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'src', 'assets', 'portraits')
OUT = os.path.join(ROOT, 'src', 'data', 'portrait-rigs.js')

# MediaPipe Face Mesh indices (468-point topology)
L_EYE = dict(outer=33, inner=133, top=159, bottom=145, top2=158, top3=160)    # subject's right eye (image left)
R_EYE = dict(outer=263, inner=362, top=386, bottom=374, top2=385, top3=387)   # subject's left eye (image right)
L_BROW = [70, 63, 105, 66, 107]
R_BROW = [300, 293, 334, 296, 336]
MOUTH = dict(left=61, right=291, top=13, bottom=14, upper=0, lower=17)
NOSE, CHIN, FOREHEAD = 1, 152, 10
OVAL = [10, 338, 297, 332, 284, 251, 389, 356, 454, 323, 361, 288, 397, 365, 379, 378, 400, 377, 152, 148, 176, 149, 150, 136, 172, 58, 132, 93, 234, 127, 162, 21, 54, 103, 67, 109]

def r(v):
    return round(float(v), 4)

def main():
    rigs = {}
    mesh = mp.solutions.face_mesh.FaceMesh(static_image_mode=True, max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.4)
    files = sorted(glob.glob(os.path.join(SRC, 'TRV-*.webp')))
    missed = []
    for f in files:
        tid = os.path.splitext(os.path.basename(f))[0]
        img = cv2.imread(f, cv2.IMREAD_COLOR)
        if img is None:
            missed.append(tid); continue
        h, w = img.shape[:2]
        res = mesh.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        if not res.multi_face_landmarks:
            missed.append(tid); continue
        lm = res.multi_face_landmarks[0].landmark
        P = lambda i: (lm[i].x, lm[i].y)
        def eye(e):
            ox, oy = P(e['outer']); ix, iy = P(e['inner'])
            tops = [P(e[k])[1] for k in ('top', 'top2', 'top3')]
            return dict(x0=r(min(ox, ix)), x1=r(max(ox, ix)), cy=r((oy + iy) / 2), top=r(min(tops)), bottom=r(P(e['bottom'])[1]))
        def brow(ix):
            pts = [P(i) for i in ix]
            return dict(x0=r(min(p[0] for p in pts)), x1=r(max(p[0] for p in pts)), y=r(sum(p[1] for p in pts) / len(pts)))
        oval = np.array([P(i) for i in OVAL])
        nose = P(NOSE)
        lx = (P(L_EYE['outer'])[0] + P(L_EYE['inner'])[0]) / 2
        rx = (P(R_EYE['outer'])[0] + P(R_EYE['inner'])[0]) / 2
        # crude yaw cue: nose offset from the eye midline, as a share of inter-ocular distance
        yaw = (nose[0] - (lx + rx) / 2) / max(1e-3, abs(rx - lx))
        rigs[tid] = dict(
            w=w, h=h,
            eyeL=eye(L_EYE), eyeR=eye(R_EYE),
            browL=brow(L_BROW), browR=brow(R_BROW),
            mouth=dict(x0=r(P(MOUTH['left'])[0]), x1=r(P(MOUTH['right'])[0]), y=r((P(MOUTH['top'])[1] + P(MOUTH['bottom'])[1]) / 2),
                       upper=r(P(MOUTH['upper'])[1]), lower=r(P(MOUTH['lower'])[1])),
            nose=dict(x=r(nose[0]), y=r(nose[1])), chin=dict(x=r(P(CHIN)[0]), y=r(P(CHIN)[1])), forehead=dict(y=r(P(FOREHEAD)[1])),
            face=dict(x0=r(oval[:, 0].min()), x1=r(oval[:, 0].max()), y0=r(oval[:, 1].min()), y1=r(oval[:, 1].max())),
            yaw=r(yaw))
    header = ('// GENERATED by scripts/extract-portrait-rigs.py (MediaPipe Face Mesh, offline, build time) — do not edit by hand.\n'
              '// Normalised (0–1) anchor points for each portrait so the runtime avatar can blink, breathe and move its jaw.\n'
              '// Presentation data only: never read by an engine, never a verdict input.\n')
    with open(OUT, 'w') as fh:
        fh.write(header + 'export const PORTRAIT_RIGS = ' + json.dumps(rigs, separators=(',', ':')) + ';\n')
    print(f'rigs: {len(rigs)} / {len(files)} portraits; missed: {missed}')
    if missed:
        sys.exit(0)

if __name__ == '__main__':
    main()
