// Career progression: XP, levels, achievements, daily missions and optional challenge modes.
// All of this is meta-game bookkeeping; none of it changes legal outcomes.
import { ACHIEVEMENTS } from '../../data/achievements.js';
import { CHALLENGES, DAILY_MISSION_DEFS } from '../../data/missions.js';
import { session, state } from '../state.js';
import { dateDayNumber, hashSeed, localDateKey, makeRng } from './rng.js';
import { operationalScore, overallScore, procedureAverage } from './score-engine.js';
import { bus, notify } from '../services/bus.js';
import { simulatedBacklog } from './operation-engine.js';

export { ACHIEVEMENTS, CHALLENGES, DAILY_MISSION_DEFS };

export function careerTemplate() { return { xp: 0, completedShifts: 0, totalPassengers: 0, cleanPassengers: 0, cleanShifts: 0, sGrades: 0, realisticS: 0, secondaryClears: 0, zeroOverSecondaryShifts: 0, refugeePerfect: 0, sjpPerfect: 0, challengeWins: 0, challengeCompleted: {}, challengeStreak: 0, bestChallengeStreak: 0, scenarioCompleted: {}, scenarioBest: {}, dailyMissionCompletions: 0, dailyFullDays: 0, dailyStreak: 0, bestDailyStreak: 0, lastDailyCompleteDate: null, bestOverall: 0, difficultyCompleted: { training: false, standard: false, realistic: false }, achievements: {}, campaignsCompleted: 0, campaignPerfect: 0, campaignBest: {} }; }
export function sessionXP(s) { const bonus = ({ S: 45, A: 28, B: 14, C: 5, F: 0 })[s.grade] || 0, diff = ({ training: 0, standard: 18, realistic: 38 })[s.difficulty] || 0, challenge = s.challengeSuccess ? (s.challengeBonus || 0) : 0; return Math.max(0, (s.stats?.processed || 0) * 5 + Math.round((s.overall || 0) * .6) + bonus + diff + challenge); }
export function applySessionCareer(c, s) { c.completedShifts++; c.totalPassengers += (s.stats?.processed || 0); const reports = s.reports || []; c.cleanPassengers += reports.filter((r) => !(r.mistakes || []).length).length; if (!(s.mistakes || []).length) c.cleanShifts++; if (s.grade === 'S') c.sGrades++; if (s.grade === 'S' && s.difficulty === 'realistic') c.realisticS++; c.secondaryClears += reports.filter((r) => r.label === '입국 허가' && (r.actions || []).includes('SECONDARY')).length; if (typeof s.overSecondary === 'number' && s.overSecondary === 0) c.zeroOverSecondaryShifts++; if (reports.some((r) => (r.actions || []).includes('REFUGEE_CLAIM') && r.procedure === 100 && !(r.mistakes || []).length)) c.refugeePerfect++; if (reports.some((r) => r.label === '특사경 긴급체포' && r.procedure === 100 && !(r.mistakes || []).length)) c.sjpPerfect++; if (s.challengeId && s.challengeId !== 'none') { if (s.challengeSuccess) { c.challengeWins = (c.challengeWins || 0) + 1; if (!c.challengeCompleted) c.challengeCompleted = {}; c.challengeCompleted[s.challengeId] = (c.challengeCompleted[s.challengeId] || 0) + 1; c.challengeStreak = (c.challengeStreak || 0) + 1; c.bestChallengeStreak = Math.max(c.bestChallengeStreak || 0, c.challengeStreak); } else c.challengeStreak = 0; } if (!c.scenarioCompleted) c.scenarioCompleted = {}; if (!c.scenarioBest) c.scenarioBest = {}; const sid = s.scenarioId || 'normal'; c.scenarioCompleted[sid] = (c.scenarioCompleted[sid] || 0) + 1; c.scenarioBest[sid] = Math.max(c.scenarioBest[sid] || 0, s.overall || 0); c.bestOverall = Math.max(c.bestOverall || 0, s.overall || 0); c.difficultyCompleted[s.difficulty] = true; c.xp = (c.xp || 0) + sessionXP(s); return c; }
export function careerFromSessions(sessions) { const c = careerTemplate(); [...(sessions || [])].reverse().forEach((s) => applySessionCareer(c, s)); return c; }
export function levelInfo(xp) { xp = Math.max(0, Number(xp) || 0); const level = Math.max(1, Math.floor(Math.sqrt(xp / 250)) + 1), start = 250 * Math.pow(level - 1, 2), next = 250 * Math.pow(level, 2), pct = Math.max(0, Math.min(100, Math.round((xp - start) / Math.max(1, next - start) * 100))); return { level, start, next, pct, current: xp - start, needed: next - start }; }
export function careerTitle(level) { if (level >= 8) return '수석 시뮬레이션 심사관'; if (level >= 6) return '고급 심사관'; if (level >= 4) return '숙련 심사관'; if (level >= 3) return '독립 심사관'; if (level >= 2) return '실무 적응'; return '신규 배치'; }
export function evaluateAchievements(c) { const unlocked = []; ACHIEVEMENTS.forEach((a) => { if (!c.achievements[a.id] && a.test(c)) { c.achievements[a.id] = Date.now(); unlocked.push(a.id); } }); return unlocked; }
export function achievementById(id) { return ACHIEVEMENTS.find((a) => a.id === id); }
export function gradeRank(g) { return ({ S: 5, A: 4, B: 3, C: 2, F: 1 })[g] || 0; }

// ---- Daily missions ------------------------------------------------------------------------
export function dailyMissionIds(key = localDateKey()) { const rng = makeRng(hashSeed(key + '|DAILY_MISSIONS')); const pickG = (g) => { const a = Object.values(DAILY_MISSION_DEFS).filter((x) => x.group === g); return a[Math.floor(rng() * a.length)].id; }; return [pickG('volume'), pickG('quality'), pickG('meta')]; }
export function freshDaily(key = localDateKey()) { return { date: key, ids: dailyMissionIds(key), progress: {}, rewarded: {}, allComplete: false }; }
export function syncDailyMeta(meta) { const key = localDateKey(); if (!meta.daily || meta.daily.date !== key) meta.daily = freshDaily(key); for (const id of meta.daily.ids) { if (typeof meta.daily.progress[id] !== 'number') meta.daily.progress[id] = 0; if (typeof meta.daily.rewarded[id] !== 'boolean') meta.daily.rewarded[id] = false; } return meta.daily; }
export function missionIncrement(id, s) { const rs = s.reports || []; if (id === 'clean20') return rs.filter((r) => !(r.mistakes || []).length).length; if (id === 'secondary2') return rs.filter((r) => r.label === '입국 허가' && (r.actions || []).includes('SECONDARY')).length; if (id === 'interpreter2') return rs.filter((r) => r.interpreter).length; if (id === 'cleanShift') return !(s.mistakes || []).length ? 1 : 0; if (id === 'highOverall') return (s.overall || 0) >= 92 ? 1 : 0; if (id === 'efficient') return (s.efficiency || 0) >= 95 && (s.procedure || 0) >= 95 ? 1 : 0; if (id === 'challengeWin') return s.challengeSuccess ? 1 : 0; if (id === 'specialPerfect') return rs.some((r) => ((r.actions || []).includes('REFUGEE_CLAIM') || r.label === '특사경 긴급체포') && r.procedure === 100 && !(r.mistakes || []).length) ? 1 : 0; if (id === 'realistic') return s.difficulty === 'realistic' && (s.overall || 0) >= 88 ? 1 : 0; return 0; }
export function updateDailyStreak(c, date) { if (c.lastDailyCompleteDate === date) return; const prev = c.lastDailyCompleteDate; const gap = prev ? dateDayNumber(date) - dateDayNumber(prev) : 999; c.dailyStreak = gap === 1 ? (c.dailyStreak || 0) + 1 : 1; c.bestDailyStreak = Math.max(c.bestDailyStreak || 0, c.dailyStreak); c.lastDailyCompleteDate = date; c.dailyFullDays = (c.dailyFullDays || 0) + 1; }
export function applyDailyMissions(meta, s) { const d = syncDailyMeta(meta), rewards = []; for (const id of d.ids) { const def = DAILY_MISSION_DEFS[id], before = d.progress[id] || 0, inc = missionIncrement(id, s); d.progress[id] = Math.min(def.target, before + inc); if (d.progress[id] >= def.target && !d.rewarded[id]) { d.rewarded[id] = true; meta.career.xp = (meta.career.xp || 0) + def.reward; meta.career.dailyMissionCompletions = (meta.career.dailyMissionCompletions || 0) + 1; rewards.push({ id, name: def.name, xp: def.reward }); } } if (d.ids.every((id) => d.progress[id] >= DAILY_MISSION_DEFS[id].target) && !d.allComplete) { d.allComplete = true; meta.career.xp = (meta.career.xp || 0) + 40; updateDailyStreak(meta.career, d.date); rewards.push({ id: 'daily_all', name: '오늘의 미션 3종 완료', xp: 40 }); } return rewards; }
// Projected daily progress including the in-progress shift (for the mission board).
export function dailySnapshot(meta, project = false) { const d = syncDailyMeta(meta), p = { ...d.progress }; if (project && state?.started) { const pseudo = { reports: state.reports || [], mistakes: state.mistakes || [], overall: overallScore(), efficiency: state.efficiency, procedure: procedureAverage(), challengeSuccess: challengeCfg().id !== 'none' && challengeEvaluation(false).success, difficulty: state.difficulty }; for (const id of d.ids) p[id] = Math.min(DAILY_MISSION_DEFS[id].target, (p[id] || 0) + missionIncrement(id, pseudo)); } return { meta, d, progress: p }; }

// ---- Challenges ----------------------------------------------------------------------------
export function challengeCfg(id = state?.challengeId || 'none') { return CHALLENGES[id] || CHALLENGES.none; }
export function setChallenge(id) { if (state.started) { notify.toast('근무 시작 후에는 도전과제를 변경할 수 없습니다.'); return false; } if (!CHALLENGES[id]) return false; state.challengeId = id; state.challengeApplied = false; bus.emit('ops'); return true; }
export function challengeInterpreterCases() { return (state.reports || []).filter((r) => r.interpreter).length; }
export function challengeSpecialStatus() { const rs = state.reports || []; const refugee = rs.some((r) => (r.actions || []).includes('REFUGEE_CLAIM') && r.procedure === 100 && !(r.mistakes || []).length); const sjp = rs.some((r) => r.label === '특사경 긴급체포' && r.procedure === 100 && !(r.mistakes || []).length); return { refugee, sjp }; }
export function challengeEvaluation(final = false) {
  const c = challengeCfg(); if (c.id === 'none') return { success: false, pct: 0, detail: '일반 근무 · 추가 도전 없음', bonus: 0 }; const procedure = procedureAverage(), overall = overallScore(), ops = operationalScore(); let success = false, pct = 0, detail = '';
  if (c.id === 'proportion') { const a = state.overSecondary === 0 ? 1 : 0, b = Math.min(1, state.proportionality / 96), d = Math.min(1, procedure / 95); pct = Math.round((a + b + d) / 3 * 100); success = final && a && state.proportionality >= 96 && procedure >= 95; detail = `과잉재심 ${state.overSecondary}회 · 비례성 ${state.proportionality} · 절차 ${procedure}`; }
  if (c.id === 'congestion') { const p = Math.min(1, state.pressurePeak / 55), o = Math.min(1, overall / 90), st = Math.min(1, ops / 82), clean = state.strikes === 0 ? 1 : 0; pct = Math.round((p + o + st + clean) / 4 * 100); success = final && state.pressurePeak >= 55 && overall >= 90 && ops >= 82 && state.strikes === 0; detail = `최고 대기 ${state.pressurePeak}명 · 종합 ${overall} · 운영 ${ops} · Strike ${state.strikes}`; }
  if (c.id === 'interpreter') { const n = challengeInterpreterCases(), a = Math.min(1, n / 3), b = Math.min(1, state.score / 95), d = Math.min(1, procedure / 95), clean = state.mistakes.length === 0 ? 1 : 0; pct = Math.round((a + b + d + clean) / 4 * 100); success = final && n >= 3 && state.score >= 95 && procedure >= 95 && state.mistakes.length === 0; detail = `통역 사용 종결 ${n}/3건 · 법률 ${state.score} · 절차 ${procedure} · 오류 ${state.mistakes.length}`; }
  if (c.id === 'specialist') { const x = challengeSpecialStatus(), a = x.refugee ? 1 : 0, b = x.sjp ? 1 : 0, d = Math.min(1, state.score / 95); pct = Math.round((a + b + d) / 3 * 100); success = final && x.refugee && x.sjp && state.score >= 95; detail = `난민 ${x.refugee ? '완료' : '미완료'} · 특사경 ${x.sjp ? '완료' : '미완료'} · 법률 ${state.score}`; }
  if (c.id === 'perfect') { const clean = state.mistakes.length === 0 && state.strikes === 0 ? 1 : 0, a = Math.min(1, state.score / 100), b = Math.min(1, procedure / 100); pct = Math.round((clean + a + b) / 3 * 100); success = final && clean && state.score === 100 && procedure === 100; detail = `오류 ${state.mistakes.length} · Strike ${state.strikes} · 법률 ${state.score} · 절차 ${procedure}`; }
  if (!final) { const workPct = state.started ? Math.round((state.stats.processed / Math.max(1, session.queue.length)) * 100) : 0; pct = Math.min(pct, workPct); }
  return { success: !!success, pct: Math.min(100, pct), detail, bonus: c.bonus };
}
export function applyChallengeStart() { if (state.challengeApplied) return; state.challengeApplied = true; const c = challengeCfg(); if (c.id === 'congestion') { state.backlogOffset += 18; state.pressurePeak = Math.max(state.pressurePeak, simulatedBacklog()); state.eventHistory.push({ at: 0, type: 'CHALLENGE', title: '특별근무 · 혼잡 대응', effect: '시작 대기 +18명', status: '도전' }); } bus.emit('ops'); if (c.id !== 'none') { notify.announce('특별 근무 도전', `${c.name} 목표가 활성화되었습니다.`, 'CHALLENGE', 2200); notify.toast(`도전 시작 · ${c.name}`); } }
